# -*- coding: utf-8 -*-
"""
Entity configuration for Discovery Uttarakhand dataset.
Every entity maps to a real Wikipedia/Wikivoyage article which serves as the
verifiable source. Districts/regions are curated and cross-checked against
Wikidata P131 (located in administrative territorial entity) at collection time.
"""

LAST_VERIFIED = "2026-09-09"

# type: destination | spiritual | cultural | activity
# fields: name, titles (list of fallback Wikipedia titles), district, region,
#         search_ctx (extra terms for Commons image search), category (for activities),
#         location (display location for spiritual/cultural/activity entries),
#         highlight_candidates (phrases verified against source text before inclusion)

DESTINATIONS = [
    dict(name="Dehradun", titles=["Dehradun"], district="Dehradun", region="Garhwal",
         search_ctx="Dehradun city",
         highlight_candidates=["Forest Research Institute", "Robber's Cave", "Sahastradhara", "Tapkeshwar Temple", "Mindrolling Monastery", "Clock Tower", "Malsi Deer Park"]),
    dict(name="Mussoorie", titles=["Mussoorie"], district="Dehradun", region="Garhwal",
         search_ctx="Mussoorie hill station",
         highlight_candidates=["Kempty Falls", "Gun Hill", "Mall Road", "Lal Tibba", "Landour", "Company Garden", "Christ Church"]),
    dict(name="Chakrata", titles=["Chakrata"], district="Dehradun", region="Garhwal",
         search_ctx="Chakrata Uttarakhand",
         highlight_candidates=["Tiger Falls", "Deoban"]),
    dict(name="Kanatal", titles=["Kanatal"], district="Tehri Garhwal", region="Garhwal",
         search_ctx="Kanatal Uttarakhand", highlight_candidates=["Surkanda Devi Temple"]),
    dict(name="Dhanaulti", titles=["Dhanaulti"], district="Tehri Garhwal", region="Garhwal",
         search_ctx="Dhanaulti Uttarakhand", highlight_candidates=["Surkanda Devi Temple", "Eco park"]),
    dict(name="New Tehri", titles=["New Tehri", "Tehri"], district="Tehri Garhwal", region="Garhwal",
         search_ctx="New Tehri town Tehri dam",
         highlight_candidates=["Tehri Dam", "Tehri Lake"]),
    dict(name="Rishikesh", titles=["Rishikesh"], district="Dehradun", region="Garhwal",
         search_ctx="Rishikesh Uttarakhand",
         highlight_candidates=["Laxman Jhula", "Ram Jhula", "Triveni Ghat", "Parmarth Niketan", "Neelkanth Mahadev Temple", "Beatles Ashram"]),
    dict(name="Haridwar", titles=["Haridwar"], district="Haridwar", region="Garhwal",
         search_ctx="Haridwar Uttarakhand",
         highlight_candidates=["Har Ki Pauri", "Mansa Devi Temple", "Chandi Devi Temple", "Maya Devi Temple"]),
    dict(name="Lansdowne", titles=["Lansdowne, Uttarakhand"], district="Pauri Garhwal", region="Garhwal",
         search_ctx="Lansdowne Uttarakhand cantonment",
         highlight_candidates=["Bhulla Lake", "Tip-in-Top", "St. Mary's Church", "Garhwali Museum"]),
    dict(name="Auli", titles=["Auli, India"], district="Chamoli", region="Garhwal",
         search_ctx="Auli skiing Uttarakhand",
         highlight_candidates=["Auli Ropeway", "Gurso Bugyal", "Kwani Bugyal"]),
    dict(name="Joshimath", titles=["Joshimath"], district="Chamoli", region="Garhwal",
         search_ctx="Joshimath Uttarakhand",
         highlight_candidates=["Shankaracharya Math", "Narsingh Temple", "Auli"]),
    dict(name="Chopta", titles=["Chopta"], district="Rudraprayag", region="Garhwal",
         search_ctx="Chopta Uttarakhand Tungnath",
         highlight_candidates=["Tungnath", "Chandrashila", "Deoria Tal"]),
    dict(name="Uttarkashi", titles=["Uttarkashi"], district="Uttarkashi", region="Garhwal",
         search_ctx="Uttarkashi town",
         highlight_candidates=["Nachiketa Tal", "Dayara Bugyal"]),
    dict(name="Rudraprayag", titles=["Rudraprayag"], district="Rudraprayag", region="Garhwal",
         search_ctx="Rudraprayag Uttarakhand confluence",
         highlight_candidates=["Koteshwar Mahadev Temple", "Rudranath"]),
    dict(name="Harsil", titles=["Harsil"], district="Uttarkashi", region="Garhwal",
         search_ctx="Harsil Uttarakhand Bhagirathi",
         highlight_candidates=["Gangotri", "Dharali"]),
    dict(name="Valley of Flowers National Park", titles=["Valley of Flowers National Park"], district="Chamoli", region="Garhwal",
         search_ctx="Valley of Flowers Uttarakhand Nanda Devi",
         highlight_candidates=["Hemkund Sahib", "Nanda Devi National Park", "Pushpawati River"]),
    dict(name="Nainital", titles=["Nainital"], district="Nainital", region="Kumaon",
         search_ctx="Nainital lake Uttarakhand",
         highlight_candidates=["Naini Lake", "Naina Peak", "Snow View Point", "Tiffin Top", "Governor's House", "Pt. G.B. Pant High Altitude Zoo", "St. John in the Wilderness"]),
    dict(name="Bhimtal", titles=["Bhimtal"], district="Nainital", region="Kumaon",
         search_ctx="Bhimtal lake Uttarakhand",
         highlight_candidates=["Bhimtal Lake", "Bhimeshwar Mahadev Temple", "Aquarium Island"]),
    dict(name="Sattal", titles=["Sattal"], district="Nainital", region="Kumaon",
         search_ctx="Sattal lakes Uttarakhand",
         highlight_candidates=["Butterfly museum", "Garud Tal"]),
    dict(name="Naukuchiatal", titles=["Naukuchiatal"], district="Nainital", region="Kumaon",
         search_ctx="Naukuchiatal lake Uttarakhand", highlight_candidates=[]),
    dict(name="Almora", titles=["Almora"], district="Almora", region="Kumaon",
         search_ctx="Almora town Uttarakhand",
         highlight_candidates=["Kasar Devi", "Chitai Temple", "Nanda Devi Temple", "Bright End Corner", "Govind Ballabh Pant Museum"]),
    dict(name="Ranikhet", titles=["Ranikhet"], district="Almora", region="Kumaon",
         search_ctx="Ranikhet Uttarakhand",
         highlight_candidates=["Jhula Devi Temple", "Chaubatia Gardens", "Golf Course", "Mankameshwar Temple", "Haidakhan Babaji"]),
    dict(name="Kausani", titles=["Kausani"], district="Bageshwar", region="Kumaon",
         search_ctx="Kausani Uttarakhand Himalaya",
         highlight_candidates=["Anasakti Ashram", "Rudradhari Falls", "Baijnath Temple"]),
    dict(name="Mukteshwar", titles=["Mukteshwar"], district="Nainital", region="Kumaon",
         search_ctx="Mukteshwar Uttarakhand",
         highlight_candidates=["Mukteshwar Temple", "Chauli Ki Jali", "Indian Veterinary Research Institute"]),
    dict(name="Binsar", titles=["Binsar Wildlife Sanctuary", "Binsar"], district="Almora", region="Kumaon",
         search_ctx="Binsar Uttarakhand sanctuary",
         highlight_candidates=["Zero Point", "Khali Estate"]),
    dict(name="Pithoragarh", titles=["Pithoragarh"], district="Pithoragarh", region="Kumaon",
         search_ctx="Pithoragarh Uttarakhand town",
         highlight_candidates=["Pithoragarh Fort", "Chandak", "Mostamanu"]),
    dict(name="Munsiyari", titles=["Munsiyari"], district="Pithoragarh", region="Kumaon",
         search_ctx="Munsiyari Uttarakhand Himalaya",
         highlight_candidates=["Panchachuli", "Khaliya Top", "Birthi Falls", "Maheshwari Kund"]),
    dict(name="Chaukori", titles=["Chaukori"], district="Pithoragarh", region="Kumaon",
         search_ctx="Chaukori Uttarakhand", highlight_candidates=[]),
    dict(name="Lohaghat", titles=["Lohaghat"], district="Champawat", region="Kumaon",
         search_ctx="Lohaghat Uttarakhand", highlight_candidates=["Mayawati Ashram", "Advaita Ashrama"]),
    dict(name="Ramnagar", titles=["Ramnagar, Uttarakhand"], district="Nainital", region="Kumaon",
         search_ctx="Ramnagar Uttarakhand Corbett",
         highlight_candidates=["Jim Corbett National Park", "Corbett Falls", "Garjiya Devi Temple"]),
    dict(name="Jim Corbett National Park", titles=["Jim Corbett National Park"], district="Nainital", region="Garhwal",
         search_ctx="Jim Corbett National Park tiger",
         highlight_candidates=["Dhikala", "Bijrani", "Corbett Falls", "Kalagarh Dam"]),
    dict(name="Rajaji National Park", titles=["Rajaji National Park"], district="Haridwar", region="Garhwal",
         search_ctx="Rajaji National Park elephant tiger",
         highlight_candidates=["Chilla", "Motichur"]),
    dict(name="Bageshwar", titles=["Bageshwar"], district="Bageshwar", region="Kumaon",
         search_ctx="Bageshwar Uttarakhand town",
         highlight_candidates=["Baijnath Temple", "Pindari Glacier", "Kafni Glacier"]),
    dict(name="Kedarnath", titles=["Kedarnath"], district="Rudraprayag", region="Garhwal",
         search_ctx="Kedarnath town Uttarakhand",
         highlight_candidates=["Kedarnath Temple", "Chorabari Glacier", "Vasuki Tal", "Gandikota"]),
    dict(name="Badrinath", titles=["Badrinath"], district="Chamoli", region="Garhwal",
         search_ctx="Badrinath town Uttarakhand",
         highlight_candidates=["Badrinath Temple", "Tapt Kund", "Neelkanth peak", "Charanpaduka"]),
    dict(name="Gangotri", titles=["Gangotri"], district="Uttarkashi", region="Garhwal",
         search_ctx="Gangotri temple town Uttarakhand",
         highlight_candidates=["Gangotri Temple", "Bhagirathi", "Gaumukh"]),
    dict(name="Yamunotri", titles=["Yamunotri"], district="Uttarkashi", region="Garhwal",
         search_ctx="Yamunotri temple Uttarakhand",
         highlight_candidates=["Yamunotri Temple", "Surya Kund", "Divya Shila", "Janki Chatti"]),
]

SPIRITUAL = [
    dict(name="Kedarnath Temple", titles=["Kedarnath Temple"], district="Rudraprayag", region="Garhwal",
         location="Kedarnath", search_ctx="Kedarnath Temple",
         highlight_candidates=["Jyotirlinga", "Char Dham", "Adi Shankara", "Panch Kedar"]),
    dict(name="Badrinath Temple", titles=["Badrinath Temple"], district="Chamoli", region="Garhwal",
         location="Badrinath", search_ctx="Badrinath Temple",
         highlight_candidates=["Chota Char Dham", "Divya Desam", "Adi Shankara", "Tapt Kund"]),
    dict(name="Gangotri Temple", titles=["Gangotri"], district="Uttarkashi", region="Garhwal",
         location="Gangotri", search_ctx="Gangotri temple",
         highlight_candidates=["Chota Char Dham", "Bhagirathi"]),
    dict(name="Yamunotri Temple", titles=["Yamunotri Temple", "Yamunotri"], district="Uttarkashi", region="Garhwal",
         location="Yamunotri", search_ctx="Yamunotri temple",
         highlight_candidates=["Chota Char Dham", "Surya Kund", "Divya Shila"]),
    dict(name="Hemkund Sahib", titles=["Hemkund Sahib"], district="Chamoli", region="Garhwal",
         location="Near Joshimath", search_ctx="Hemkund Sahib Gurudwara",
         highlight_candidates=["Gurudwara", "Lakshman", "Glacier lake"]),
    dict(name="Tungnath", titles=["Tungnath"], district="Rudraprayag", region="Garhwal",
         location="Near Chopta", search_ctx="Tungnath temple",
         highlight_candidates=["Panch Kedar", "Chandrashila", "highest Shiva"]),
    dict(name="Madhyamaheshwar", titles=["Madhyamaheshwar"], district="Rudraprayag", region="Garhwal",
         location="Near Guptkashi", search_ctx="Madhyamaheshwar temple",
         highlight_candidates=["Panch Kedar"]),
    dict(name="Rudranath", titles=["Rudranath"], district="Chamoli", region="Garhwal",
         location="Near Gopeshwar", search_ctx="Rudranath temple Uttarakhand",
         highlight_candidates=["Panch Kedar"]),
    dict(name="Kalpeshwar", titles=["Kalpeshwar"], district="Chamoli", region="Garhwal",
         location="Near Joshimath / Urgam Valley", search_ctx="Kalpeshwar temple",
         highlight_candidates=["Panch Kedar"]),
    dict(name="Jageshwar", titles=["Jageshwar"], district="Almora", region="Kumaon",
         location="Jageshwar", search_ctx="Jageshwar temples Almora",
         highlight_candidates=["Jyotirlinga", "Archaeological Survey of India", "Dandeshwar"]),
    dict(name="Baijnath Temple", titles=["Baijnath Temple, Bageshwar", "Baijnath, Uttarakhand"], district="Bageshwar", region="Kumaon",
         location="Baijnath, near Bageshwar", search_ctx="Baijnath temple Bageshwar Uttarakhand",
         highlight_candidates=["Katyuri"]),
    dict(name="Kainchi Dham", titles=["Kainchi Dham"], district="Nainital", region="Kumaon",
         location="Near Bhowali", search_ctx="Kainchi Dham Neem Karoli Baba",
         highlight_candidates=["Neem Karoli Baba", "Hanuman"]),
    dict(name="Patal Bhuvaneshwar", titles=["Patal Bhuvaneshwar"], district="Pithoragarh", region="Kumaon",
         location="Gangolihat", search_ctx="Patal Bhuvaneshwar cave temple",
         highlight_candidates=["cave", "Shiva", "Adi Shankara"]),
    dict(name="Mansa Devi Temple", titles=["Mansa Devi Temple, Haridwar"], district="Haridwar", region="Garhwal",
         location="Haridwar", search_ctx="Mansa Devi Temple Haridwar",
         highlight_candidates=["Bilwa Tirtha", "ropeway"]),
    dict(name="Chandi Devi Temple", titles=["Chandi Devi Temple, Haridwar"], district="Haridwar", region="Garhwal",
         location="Haridwar", search_ctx="Chandi Devi Temple Haridwar",
         highlight_candidates=["Neel Parvat", "ropeway"]),
    dict(name="Maya Devi Temple", titles=["Maya Devi Temple, Haridwar"], district="Haridwar", region="Garhwal",
         location="Haridwar", search_ctx="Maya Devi Temple Haridwar",
         highlight_candidates=["Shakti Peetha"]),
    dict(name="Har Ki Pauri", titles=["Har Ki Pauri"], district="Haridwar", region="Garhwal",
         location="Haridwar", search_ctx="Har Ki Pauri Haridwar Ganga",
         highlight_candidates=["Ganga Aarti", "Kumbh Mela"]),
    dict(name="Parmarth Niketan", titles=["Parmarth Niketan"], district="Dehradun", region="Garhwal",
         location="Rishikesh", search_ctx="Parmarth Niketan Rishikesh ashram",
         highlight_candidates=["Ganga Aarti", "International Yoga Festival"]),
    dict(name="Triveni Ghat", titles=["Triveni Ghat"], district="Dehradun", region="Garhwal",
         location="Rishikesh", search_ctx="Triveni Ghat Rishikesh",
         highlight_candidates=["Ganga Aarti"]),
    dict(name="Neelkanth Mahadev Temple", titles=["Neelkanth Mahadev Temple"], district="Pauri Garhwal", region="Garhwal",
         location="Near Rishikesh", search_ctx="Neelkanth Mahadev Temple Rishikesh",
         highlight_candidates=["Neelkanth", "Samudra Manthan"]),
    dict(name="Kasar Devi", titles=["Kasar Devi"], district="Almora", region="Kumaon",
         location="Near Almora", search_ctx="Kasar Devi temple Almora",
         highlight_candidates=["Van Allen", "hippie", "Swami Vivekananda"]),
    dict(name="Chitai Golu Devta Temple", titles=["Chitai Golu Devta Temple", "Golu Devata", "Chitai"], district="Almora", region="Kumaon",
         location="Chitai, near Almora", search_ctx="Chitai Golu Devta temple Almora",
         highlight_candidates=["Golu Devta", "bells"]),
    dict(name="Surkanda Devi Temple", titles=["Surkanda Devi Temple", "Surkanda Devi"], district="Tehri Garhwal", region="Garhwal",
         location="Near Dhanaulti / Kaddukhal", search_ctx="Surkanda Devi temple Uttarakhand",
         highlight_candidates=["Sati", "Ganga Dussehra"]),
    dict(name="Dhari Devi", titles=["Dhari Devi"], district="Pauri Garhwal", region="Garhwal",
         location="On the Alaknanda near Srinagar", search_ctx="Dhari Devi temple Alaknanda",
         highlight_candidates=[]),
    dict(name="Katarmal Sun Temple", titles=["Katarmal Sun Temple", "Katarmal"], district="Almora", region="Kumaon",
         location="Katarmal, near Almora", search_ctx="Katarmal Sun Temple Almora",
         highlight_candidates=["Surya", "Archaeological Survey of India"]),
    dict(name="Tapkeshwar Temple", titles=["Tapkeshwar Temple"], district="Dehradun", region="Garhwal",
         location="Dehradun", search_ctx="Tapkeshwar Mahadev Temple Dehradun",
         highlight_candidates=["Shiva", "Tons River", "cave", "shivalinga"]),
    dict(name="Kedarnath Wildlife Sanctuary Temples", titles=[], skip=True) if False else None,
]

SPIRITUAL = [s for s in SPIRITUAL if s]

CULTURAL = [
    dict(name="Forest Research Institute", titles=["Forest Research Institute (India)", "Forest Research Institute"], district="Dehradun", region="Garhwal",
         location="Dehradun", search_ctx="Forest Research Institute Dehradun building",
         highlight_candidates=["Heritage", "National Heritage", "Gothic", "museum"]),
    dict(name="Gurney House", titles=["Gurney House"], district="Nainital", region="Kumaon",
         location="Nainital", search_ctx="Gurney House Nainital Corbett",
         highlight_candidates=["Jim Corbett", "Ayar"]),
    dict(name="Advaita Ashrama (Mayawati)", titles=["Advaita Ashrama"], district="Champawat", region="Kumaon",
         location="Mayawati, near Lohaghat", search_ctx="Advaita Ashrama Mayawati Lohaghat",
         highlight_candidates=["Swami Vivekananda", "Ramakrishna Order", "library"]),
    dict(name="St. John in the Wilderness Church", titles=["St. John in the Wilderness Church, Nainital", "St. John in the Wilderness"], district="Nainital", region="Kumaon",
         location="Nainital", search_ctx="St John in the Wilderness church Nainital",
         highlight_candidates=["1844", "Victim of landslide"]),
    dict(name="Dwarahat", titles=["Dwarahat"], district="Almora", region="Kumaon",
         location="Dwarahat", search_ctx="Dwarahat temples Uttarakhand",
         highlight_candidates=["Katyuri", "Archaeological Survey of India"]),
    dict(name="G.B. Pant High Altitude Zoo", titles=["Pt. G.B. Pant High Altitude Zoo", "G. B. Pant High Altitude Zoo"], district="Nainital", region="Kumaon",
         location="Nainital", search_ctx="Pant High Altitude Zoo Nainital",
         highlight_candidates=["snow leopard", "Sher Kapoor"]),
    dict(name="Christ Church, Mussoorie", titles=["Christ Church, Mussoorie"], district="Dehradun", region="Garhwal",
         location="Mussoorie", search_ctx="Christ Church Mussoorie",
         highlight_candidates=["1844", "Gothic"]),
]

ACTIVITIES = [
    dict(name="Roopkund Trek", titles=["Roopkund"], district="Chamoli", region="Garhwal",
         location="Near Wan, Chamoli", category="Trekking", search_ctx="Roopkund lake Uttarakhand",
         highlight_candidates=["skeleton", "Nanda Devi Raj Jat", "juniper"]),
    dict(name="Har Ki Dun Trek", titles=["Har ki Dun", "Har Ki Dun"], district="Uttarkashi", region="Garhwal",
         location="Sankri, Uttarkashi", category="Trekking", search_ctx="Har Ki Dun trek Uttarakhand",
         highlight_candidates=["Swargarohini", "Supin", "Osla"]),
    dict(name="Nag Tibba Trek", titles=["Nag Tibba"], district="Dehradun", region="Garhwal",
         location="Near Mussoorie / Pantwari", category="Trekking", search_ctx="Nag Tibba peak Uttarakhand",
         highlight_candidates=["Nag Devta", "Black Mountain"]),
    dict(name="Dayara Bugyal Trek", titles=["Dayara Bugyal"], district="Uttarkashi", region="Garhwal",
         location="Raithal / Barsu, Uttarkashi", category="Trekking", search_ctx="Dayara Bugyal Uttarakhand",
         highlight_categories=None, highlight_candidates=["Gidara", "Barnala Tal"]),
    dict(name="Dodital Trek", titles=["Dodital", "Dodital Lake"], district="Uttarkashi", region="Garhwal",
         location="Near Sangam Chatti / Darwa", category="Trekking", search_ctx="Dodital lake Uttarakhand",
         highlight_candidates=["Ganesha", "trout", "Darwa Pass"]),
    dict(name="Kedartal Trek", titles=["Kedartal"], district="Uttarkashi", region="Garhwal",
         location="Near Gangotri", category="Trekking", search_ctx="Kedartal lake Gangotri",
         highlight_candidates=["Thalay Sagar", "Bhrigupanth"]),
    dict(name="Gaumukh–Tapovan Trek", titles=["Gangotri Glacier"], district="Uttarkashi", region="Garhwal",
         location="Gangotri to Gaumukh", category="Trekking", search_ctx="Gangotri glacier Gaumukh Tapovan",
         highlight_candidates=["Gaumukh", "Tapovan", "Bhagirathi", "Shivling"]),
    dict(name="Deoria Tal Trek", titles=["Deoria Tal"], district="Rudraprayag", region="Garhwal",
         location="Sari village, near Ukhimath", category="Trekking", search_ctx="Deoria Tal lake Uttarakhand",
         highlight_candidates=["Chaukhamba", "Ukhimath"]),
    dict(name="Pindari Glacier Trek", titles=["Pindari Glacier"], district="Bageshwar", region="Kumaon",
         location="Loharkhet / Khati, Bageshwar", category="Trekking", search_ctx="Pindari glacier Uttarakhand",
         highlight_candidates=["Kafni", "Zero Point", "Khati"]),
    dict(name="Milam Glacier Trek", titles=["Milam Glacier"], district="Pithoragarh", region="Kumaon",
         location="Munsiyari", category="Trekking", search_ctx="Milam glacier Uttarakhand Munsiyari",
         highlight_candidates=["Johar valley", "Milam village", "Nanda Devi"]),
    dict(name="Kempty Falls Visit", titles=["Kempty Falls"], district="Tehri Garhwal", region="Garhwal",
         location="13 km from Mussoorie", category="Waterfalls & Sightseeing", search_ctx="Kempty Falls Mussoorie",
         highlight_candidates=["Mussoorie", "Chakrata Road"]),
    dict(name="Nanda Devi Raj Jat", titles=["Nanda Devi Raj Jat"], district="Chamoli", region="Garhwal",
         location="Nauti to Roopkund (Chamoli)", category="Pilgrimage / Festival", search_ctx="Nanda Devi Raj Jat yatra Uttarakhand",
         extra_tokens=["roopkund", "bedni", "nauti"],
         highlight_candidates=["Roopkund", "Himalayan Mahakumbh", "Nauti", "Kuari Pass"]),
    dict(name="Chandrashila Trek", titles=["Chandrashila"], district="Rudraprayag", region="Garhwal",
         location="Above Tungnath, near Chopta", category="Trekking", search_ctx="Chandrashila peak Tungnath",
         extra_tokens=["chandrasila"],
         highlight_candidates=["Tungnath", "Nanda Devi", "Trishul", "Kedarnath"]),
    dict(name="Chota Char Dham Yatra", titles=["Chota Char Dham"], district="Multiple (Uttarakhand)", region="Garhwal",
         location="Yamunotri, Gangotri, Kedarnath, Badrinath", category="Pilgrimage", search_ctx="Char Dham Uttarakhand yatra",
         extra_tokens=["yamunotri", "gangotri", "kedarnath", "badrinath"],
         highlight_candidates=["Yamunotri", "Gangotri", "Kedarnath", "Badrinath", "Adi Shankara"]),
    dict(name="Bungee Jumping at Mohan Chatti", titles=[], wikivoyage="Rishikesh", district="Dehradun", region="Garhwal",
         location="Mohan Chatti, near Rishikesh", category="Adventure Sports", search_ctx="bungee jumping Mohan Chatti Rishikesh",
         extra_tokens=["bungee"],
         highlight_candidates=["bungee", "flying fox", "giant swing"]),
    dict(name="Skiing in Auli", titles=["Auli, India"], district="Chamoli", region="Garhwal",
         location="Auli, near Joshimath", category="Skiing", search_ctx="Auli skiing slopes Uttarakhand",
         extra_tokens=["ski"],
         highlight_candidates=["ropeway", "Gurso Bugyal", "artificial lake"]),
    dict(name="Boating on Naini Lake", titles=["Naini Lake"], district="Nainital", region="Kumaon",
         location="Nainital", category="Boating", search_ctx="Naini Lake Nainital boating",
         extra_tokens=["nainital", "boat"],
         highlight_candidates=["yachting", "Balia Tal"]),
    dict(name="Jeep Safari in Jim Corbett National Park", titles=["Jim Corbett National Park"], district="Nainital", region="Garhwal",
         location="Ramnagar", category="Wildlife Safari", search_ctx="Jim Corbett National Park safari tiger",
         extra_tokens=["corbett", "tiger", "safari"],
         highlight_candidates=["Bengal tiger", "Dhikala", "Bijrani", "Jhirna"]),
    dict(name="Wildlife Safari in Rajaji National Park", titles=["Rajaji National Park"], district="Haridwar", region="Garhwal",
         location="Haridwar–Dehradun range", category="Wildlife Safari", search_ctx="Rajaji National Park safari elephant",
         extra_tokens=["rajaji", "elephant"],
         highlight_candidates=["elephant", "tiger", "Chilla"]),
    dict(name="White-Water Rafting in Rishikesh", titles=[], wikivoyage="Rishikesh", district="Dehradun", region="Garhwal",
         location="Rishikesh (Brahmapuri–Shivpuri stretch)", category="River Rafting", search_ctx="rafting Ganga Rishikesh",
         extra_tokens=["rafting", "kaudiyala", "shivpuri"],
         highlight_candidates=["Shivpuri", "Marine Drive", "Grade"]),
]
