# -*- coding: utf-8 -*-
"""
Entity configuration for Discovery Uttarakhand dataset.
Every entity maps to a real Wikipedia/Wikivoyage article which serves as the
verifiable source. Districts/regions are curated and cross-checked against
Wikidata P131 (located in administrative territorial entity) at collection time.
"""

LAST_VERIFIED = "2026-09-09"

# type: destination | spiritual | cultural | activity
# fields: name, titles (list of fallback Wikipedia titles), district, region,
#         search_ctx (extra terms for Commons image search), category (for activities),
#         location (display location for spiritual/cultural/activity entries),
#         highlight_candidates (phrases verified against source text before inclusion)

DESTINATIONS = [
    dict(name="Dehradun", titles=["Dehradun"], district="Dehradun", region="Garhwal",
         search_ctx="Dehradun city",
         highlight_candidates=["Forest Research Institute", "Robber's Cave", "Sahastradhara", "Tapkeshwar Temple", "Mindrolling Monastery", "Clock Tower", "Malsi Deer Park"]),
    dict(name="Mussoorie", titles=["Mussoorie"], district="Dehradun", region="Garhwal",
         search_ctx="Mussoorie hill station",
         highlight_candidates=["Kempty Falls", "Gun Hill", "Mall Road", "Lal Tibba", "Landour", "Company Garden", "Christ Church"]),
    dict(name="Chakrata", titles=["Chakrata"], district="Dehradun", region="Garhwal",
         search_ctx="Chakrata Uttarakhand",
         highlight_candidates=["Tiger Falls", "Deoban"]),
    dict(name="Kanatal", titles=["Kanatal"], district="Tehri Garhwal", region="Garhwal",
         search_ctx="Kanatal Uttarakhand", highlight_candidates=["Surkanda Devi Temple"]),
    dict(name="Dhanaulti", titles=["Dhanaulti"], district="Tehri Garhwal", region="Garhwal",
         search_ctx="Dhanaulti Uttarakhand", highlight_candidates=["Surkanda Devi Temple", "Eco park"]),
    dict(name="New Tehri", titles=["New Tehri", "Tehri"], district="Tehri Garhwal", region="Garhwal",
         search_ctx="New Tehri town Tehri dam",
         highlight_candidates=["Tehri Dam", "Tehri Lake"]),
    dict(name="Rishikesh", titles=["Rishikesh"], district="Dehradun", region="Garhwal",
         search_ctx="Rishikesh Uttarakhand",
         highlight_candidates=["Laxman Jhula", "Ram Jhula", "Triveni Ghat", "Parmarth Niketan", "Neelkanth Mahadev Temple", "Beatles Ashram"]),
    dict(name="Haridwar", titles=["Haridwar"], district="Haridwar", region="Garhwal",
         search_ctx="Haridwar Uttarakhand",
         highlight_candidates=["Har Ki Pauri", "Mansa Devi Temple", "Chandi Devi Temple", "Maya Devi Temple"]),
    dict(name="Lansdowne", titles=["Lansdowne, Uttarakhand"], district="Pauri Garhwal", region="Garhwal",
         search_ctx="Lansdowne Uttarakhand cantonment",
         highlight_candidates=["Bhulla Lake", "Tip-in-Top", "St. Mary's Church", "Garhwali Museum"]),
    dict(name="Auli", titles=["Auli, India"], district="Chamoli", region="Garhwal",
         search_ctx="Auli skiing Uttarakhand",
         highlight_candidates=["Auli Ropeway", "Gurso Bugyal", "Kwani Bugyal"]),
    dict(name="Joshimath", titles=["Joshimath"], district="Chamoli", region="Garhwal",
         search_ctx="Joshimath Uttarakhand",
         highlight_candidates=["Shankaracharya Math", "Narsingh Temple", "Auli"]),
    dict(name="Chopta", titles=["Chopta"], district="Rudraprayag", region="Garhwal",
         search_ctx="Chopta Uttarakhand Tungnath",
         highlight_candidates=["Tungnath", "Chandrashila", "Deoria Tal"]),
    dict(name="Uttarkashi", titles=["Uttarkashi"], district="Uttarkashi", region="Garhwal",
         search_ctx="Uttarkashi town",
         highlight_candidates=["Nachiketa Tal", "Dayara Bugyal"]),
    dict(name="Rudraprayag", titles=["Rudraprayag"], district="Rudraprayag", region="Garhwal",
         search_ctx="Rudraprayag Uttarakhand confluence",
         highlight_candidates=["Koteshwar Mahadev Temple", "Rudranath"]),
    dict(name="Harsil", titles=["Harsil"], district="Uttarkashi", region="Garhwal",
         search_ctx="Harsil Uttarakhand Bhagirathi",
         highlight_candidates=["Gangotri", "Dharali"]),
    dict(name="Valley of Flowers National Park", titles=["Valley of Flowers National Park"], district="Chamoli", region="Garhwal",
         search_ctx="Valley of Flowers Uttarakhand Nanda Devi",
         highlight_candidates=["Hemkund Sahib", "Nanda Devi National Park", "Pushpawati River"]),
    dict(name="Nainital", titles=["Nainital"], district="Nainital", region="Kumaon",
         search_ctx="Nainital lake Uttarakhand",
         highlight_candidates=["Naini Lake", "Naina Peak", "Snow View Point", "Tiffin Top", "Governor's House", "Pt. G.B. Pant High Altitude Zoo", "St. John in the Wilderness"]),
    dict(name="Bhimtal", titles=["Bhimtal"], district="Nainital", region="Kumaon",
         search_ctx="Bhimtal lake Uttarakhand",
         highlight_candidates=["Bhimtal Lake", "Bhimeshwar Mahadev Temple", "Aquarium Island"]),
    dict(name="Sattal", titles=["Sattal"], district="Nainital", region="Kumaon",
         search_ctx="Sattal lakes Uttarakhand",
         highlight_candidates=["Butterfly museum", "Garud Tal"]),
    dict(name="Naukuchiatal", titles=["Naukuchiatal"], district="Nainital", region="Kumaon",
         search_ctx="Naukuchiatal lake Uttarakhand", highlight_candidates=[]),
    dict(name="Almora", titles=["Almora"], district="Almora", region="Kumaon",
         search_ctx="Almora town Uttarakhand",
         highlight_candidates=["Kasar Devi", "Chitai Temple", "Nanda Devi Temple", "Bright End Corner", "Govind Ballabh Pant Museum"]),
    dict(name="Ranikhet", titles=["Ranikhet"], district="Almora", region="Kumaon",
         search_ctx="Ranikhet Uttarakhand",
         highlight_candidates=["Jhula Devi Temple", "Chaubatia Gardens", "Golf Course", "Mankameshwar Temple", "Haidakhan Babaji"]),
    dict(name="Kausani", titles=["Kausani"], district="Bageshwar", region="Kumaon",
         search_ctx="Kausani Uttarakhand Himalaya",
         highlight_candidates=["Anasakti Ashram", "Rudradhari Falls", "Baijnath Temple"]),
    dict(name="Mukteshwar", titles=["Mukteshwar"], district="Nainital", region="Kumaon",
         search_ctx="Mukteshwar Uttarakhand",
         highlight_candidates=["Mukteshwar Temple", "Chauli Ki Jali", "Indian Veterinary Research Institute"]),
    dict(name="Binsar", titles=["Binsar Wildlife Sanctuary", "Binsar"], district="Almora", region="Kumaon",
         search_ctx="Binsar Uttarakhand sanctuary",
         highlight_candidates=["Zero Point", "Khali Estate"]),
    dict(name="Pithoragarh", titles=["Pithoragarh"], district="Pithoragarh", region="Kumaon",
         search_ctx="Pithoragarh Uttarakhand town",
         highlight_candidates=["Pithoragarh Fort", "Chandak", "Mostamanu"]),
    dict(name="Munsiyari", titles=["Munsiyari"], district="Pithoragarh", region="Kumaon",
         search_ctx="Munsiyari Uttarakhand Himalaya",
         highlight_candidates=["Panchachuli", "Khaliya Top", "Birthi Falls", "Maheshwari Kund"]),
    dict(name="Chaukori", titles=["Chaukori"], district="Pithoragarh", region="Kumaon",
         search_ctx="Chaukori Uttarakhand", highlight_candidates=[]),
    dict(name="Lohaghat", titles=["Lohaghat"], district="Champawat", region="Kumaon",
         search_ctx="Lohaghat Uttarakhand", highlight_candidates=["Mayawati Ashram", "Advaita Ashrama"]),
    dict(name="Ramnagar", titles=["Ramnagar, Uttarakhand"], district="Nainital", region="Kumaon",
         search_ctx="Ramnagar Uttarakhand Corbett",
         highlight_candidates=["Jim Corbett National Park", "Corbett Falls", "Garjiya Devi Temple"]),
    dict(name="Jim Corbett National Park", titles=["Jim Corbett National Park"], district="Nainital", region="Garhwal",
         search_ctx="Jim Corbett National Park tiger",
         highlight_candidates=["Dhikala", "Bijrani", "Corbett Falls", "Kalagarh Dam"]),
    dict(name="Rajaji National Park", titles=["Rajaji National Park"], district="Haridwar", region="Garhwal",
         search_ctx="Rajaji National Park elephant tiger",
         highlight_candidates=["Chilla", "Motichur"]),
    dict(name="Bageshwar", titles=["Bageshwar"], district="Bageshwar", region="Kumaon",
         search_ctx="Bageshwar Uttarakhand town",
         highlight_candidates=["Baijnath Temple", "Pindari Glacier", "Kafni Glacier"]),
    dict(name="Kedarnath", titles=["Kedarnath"], district="Rudraprayag", region="Garhwal",
         search_ctx="Kedarnath town Uttarakhand",
         highlight_candidates=["Kedarnath Temple", "Chorabari Glacier", "Vasuki Tal", "Gandikota"]),
    dict(name="Badrinath", titles=["Badrinath"], district="Chamoli", region="Garhwal",
         search_ctx="Badrinath town Uttarakhand",
         highlight_candidates=["Badrinath Temple", "Tapt Kund", "Neelkanth peak", "Charanpaduka"]),
    dict(name="Gangotri", titles=["Gangotri"], district="Uttarkashi", region="Garhwal",
         search_ctx="Gangotri temple town Uttarakhand",
         highlight_candidates=["Gangotri Temple", "Bhagirathi", "Gaumukh"]),
    dict(name="Yamunotri", titles=["Yamunotri"], district="Uttarkashi", region="Garhwal",
         search_ctx="Yamunotri temple Uttarakhand",
         highlight_candidates=["Yamunotri Temple", "Surya Kund", "Divya Shila", "Janki Chatti"]),
]

SPIRITUAL = [
    dict(name="Kedarnath Temple", titles=["Kedarnath Temple"], district="Rudraprayag", region="Garhwal",
         location="Kedarnath", search_ctx="Kedarnath Temple",
         highlight_candidates=["Jyotirlinga", "Char Dham", "Adi Shankara", "Panch Kedar"]),
    dict(name="Badrinath Temple", titles=["Badrinath Temple"], district="Chamoli", region="Garhwal",
         location="Badrinath", search_ctx="Badrinath Temple",
         highlight_candidates=["Chota Char Dham", "Divya Desam", "Adi Shankara", "Tapt Kund"]),
    dict(name="Gangotri Temple", titles=["Gangotri"], district="Uttarkashi", region="Garhwal",
         location="Gangotri", search_ctx="Gangotri temple",
         highlight_candidates=["Chota Char Dham", "Bhagirathi"]),
    dict(name="Yamunotri Temple", titles=["Yamunotri Temple", "Yamunotri"], district="Uttarkashi", region="Garhwal",
         location="Yamunotri", search_ctx="Yamunotri temple",
         highlight_candidates=["Chota Char Dham", "Surya Kund", "Divya Shila"]),
    dict(name="Hemkund Sahib", titles=["Hemkund Sahib"], district="Chamoli", region="Garhwal",
         location="Near Joshimath", search_ctx="Hemkund Sahib Gurudwara",
         highlight_candidates=["Gurudwara", "Lakshman", "Glacier lake"]),
    dict(name="Tungnath", titles=["Tungnath"], district="Rudraprayag", region="Garhwal",
         location="Near Chopta", search_ctx="Tungnath temple",
         highlight_candidates=["Panch Kedar", "Chandrashila", "highest Shiva"]),
    dict(name="Madhyamaheshwar", titles=["Madhyamaheshwar"], district="Rudraprayag", region="Garhwal",
         location="Near Guptkashi", search_ctx="Madhyamaheshwar temple",
         highlight_candidates=["Panch Kedar"]),
    dict(name="Rudranath", titles=["Rudranath"], district="Chamoli", region="Garhwal",
         location="Near Gopeshwar", search_ctx="Rudranath temple Uttarakhand",
         highlight_candidates=["Panch Kedar"]),
    dict(name="Kalpeshwar", titles=["Kalpeshwar"], district="Chamoli", region="Garhwal",
         location="Near Joshimath / Urgam Valley", search_ctx="Kalpeshwar temple",
         highlight_candidates=["Panch Kedar"]),
    dict(name="Jageshwar", titles=["Jageshwar"], district="Almora", region="Kumaon",
         location="Jageshwar", search_ctx="Jageshwar temples Almora",
         highlight_candidates=["Jyotirlinga", "Archaeological Survey of India", "Dandeshwar"]),
    dict(name="Baijnath Temple", titles=["Baijnath Temple, Bageshwar", "Baijnath, Uttarakhand"], district="Bageshwar", region="Kumaon",
         location="Baijnath, near Bageshwar", search_ctx="Baijnath temple Bageshwar Uttarakhand",
         highlight_candidates=["Katyuri"]),
    dict(name="Kainchi Dham", titles=["Kainchi Dham"], district="Nainital", region="Kumaon",
         location="Near Bhowali", search_ctx="Kainchi Dham Neem Karoli Baba",
         highlight_candidates=["Neem Karoli Baba", "Hanuman"]),
    dict(name="Patal Bhuvaneshwar", titles=["Patal Bhuvaneshwar"], district="Pithoragarh", region="Kumaon",
         location="Gangolihat", search_ctx="Patal Bhuvaneshwar cave temple",
         highlight_candidates=["cave", "Shiva", "Adi Shankara"]),
    dict(name="Mansa Devi Temple", titles=["Mansa Devi Temple, Haridwar"], district="Haridwar", region="Garhwal",
         location="Haridwar", search_ctx="Mansa Devi Temple Haridwar",
         highlight_candidates=["Bilwa Tirtha", "ropeway"]),
    dict(name="Chandi Devi Temple", titles=["Chandi Devi Temple, Haridwar"], district="Haridwar", region="Garhwal",
         location="Haridwar", search_ctx="Chandi Devi Temple Haridwar",
         highlight_candidates=["Neel Parvat", "ropeway"]),
    dict(name="Maya Devi Temple", titles=["Maya Devi Temple, Haridwar"], district="Haridwar", region="Garhwal",
         location="Haridwar", search_ctx="Maya Devi Temple Haridwar",
         highlight_candidates=["Shakti Peetha"]),
    dict(name="Har Ki Pauri", titles=["Har Ki Pauri"], district="Haridwar", region="Garhwal",
         location="Haridwar", search_ctx="Har Ki Pauri Haridwar Ganga",
         highlight_candidates=["Ganga Aarti", "Kumbh Mela"]),
    dict(name="Parmarth Niketan", titles=["Parmarth Niketan"], district="Dehradun", region="Garhwal",
         location="Rishikesh", search_ctx="Parmarth Niketan Rishikesh ashram",
         highlight_candidates=["Ganga Aarti", "International Yoga Festival"]),
    dict(name="Triveni Ghat", titles=["Triveni Ghat"], district="Dehradun", region="Garhwal",
         location="Rishikesh", search_ctx="Triveni Ghat Rishikesh",
         highlight_candidates=["Ganga Aarti"]),
    dict(name="Neelkanth Mahadev Temple", titles=["Neelkanth Mahadev Temple"], district="Pauri Garhwal", region="Garhwal",
         location="Near Rishikesh", search_ctx="Neelkanth Mahadev Temple Rishikesh",
         highlight_candidates=["Neelkanth", "Samudra Manthan"]),
    dict(name="Kasar Devi", titles=["Kasar Devi"], district="Almora", region="Kumaon",
         location="Near Almora", search_ctx="Kasar Devi temple Almora",
         highlight_candidates=["Van Allen", "hippie", "Swami Vivekananda"]),
    dict(name="Chitai Golu Devta Temple", titles=["Chitai Golu Devta Temple", "Golu Devata", "Chitai"], district="Almora", region="Kumaon",
         location="Chitai, near Almora", search_ctx="Chitai Golu Devta temple Almora",
         highlight_candidates=["Golu Devta", "bells"]),
    dict(name="Surkanda Devi Temple", titles=["Surkanda Devi Temple", "Surkanda Devi"], district="Tehri Garhwal", region="Garhwal",
         location="Near Dhanaulti / Kaddukhal", search_ctx="Surkanda Devi temple Uttarakhand",
         highlight_candidates=["Sati", "Ganga Dussehra"]),
    dict(name="Dhari Devi", titles=["Dhari Devi"], district="Pauri Garhwal", region="Garhwal",
         location="On the Alaknanda near Srinagar", search_ctx="Dhari Devi temple Alaknanda",
         highlight_candidates=[]),
    dict(name="Katarmal Sun Temple", titles=["Katarmal Sun Temple", "Katarmal"], district="Almora", region="Kumaon",
         location="Katarmal, near Almora", search_ctx="Katarmal Sun Temple Almora",
         highlight_candidates=["Surya", "Archaeological Survey of India"]),
    dict(name="Tapkeshwar Temple", titles=["Tapkeshwar Temple"], district="Dehradun", region="Garhwal",
         location="Dehradun", search_ctx="Tapkeshwar Mahadev Temple Dehradun",
         highlight_candidates=["Shiva", "Tons River", "cave", "shivalinga"]),
    dict(name="Kedarnath Wildlife Sanctuary Temples", titles=[], skip=True) if False else None,
]

SPIRITUAL = [s for s in SPIRITUAL if s]

CULTURAL = [
    dict(name="Forest Research Institute", titles=["Forest Research Institute (India)", "Forest Research Institute"], district="Dehradun", region="Garhwal",
         location="Dehradun", search_ctx="Forest Research Institute Dehradun building",
         highlight_candidates=["Heritage", "National Heritage", "Gothic", "museum"]),
    dict(name="Gurney House", titles=["Gurney House"], district="Nainital", region="Kumaon",
         location="Nainital", search_ctx="Gurney House Nainital Corbett",
         highlight_candidates=["Jim Corbett", "Ayar"]),
    dict(name="Advaita Ashrama (Mayawati)", titles=["Advaita Ashrama"], district="Champawat", region="Kumaon",
         location="Mayawati, near Lohaghat", search_ctx="Advaita Ashrama Mayawati Lohaghat",
         highlight_candidates=["Swami Vivekananda", "Ramakrishna Order", "library"]),
    dict(name="St. John in the Wilderness Church", titles=["St. John in the Wilderness Church, Nainital", "St. John in the Wilderness"], district="Nainital", region="Kumaon",
         location="Nainital", search_ctx="St John in the Wilderness church Nainital",
         highlight_candidates=["1844", "Victim of landslide"]),
    dict(name="Dwarahat", titles=["Dwarahat"], district="Almora", region="Kumaon",
         location="Dwarahat", search_ctx="Dwarahat temples Uttarakhand",
         highlight_candidates=["Katyuri", "Archaeological Survey of India"]),
    dict(name="G.B. Pant High Altitude Zoo", titles=["Pt. G.B. Pant High Altitude Zoo", "G. B. Pant High Altitude Zoo"], district="Nainital", region="Kumaon",
         location="Nainital", search_ctx="Pant High Altitude Zoo Nainital",
         highlight_candidates=["snow leopard", "Sher Kapoor"]),
    dict(name="Christ Church, Mussoorie", titles=["Christ Church, Mussoorie"], district="Dehradun", region="Garhwal",
         location="Mussoorie", search_ctx="Christ Church Mussoorie",
         highlight_candidates=["1844", "Gothic"]),
]

ACTIVITIES = [
    dict(name="Roopkund Trek", titles=["Roopkund"], district="Chamoli", region="Garhwal",
         location="Near Wan, Chamoli", category="Trekking", search_ctx="Roopkund lake Uttarakhand",
         highlight_candidates=["skeleton", "Nanda Devi Raj Jat", "juniper"]),
    dict(name="Har Ki Dun Trek", titles=["Har ki Dun", "Har Ki Dun"], district="Uttarkashi", region="Garhwal",
         location="Sankri, Uttarkashi", category="Trekking", search_ctx="Har Ki Dun trek Uttarakhand",
         highlight_candidates=["Swargarohini", "Supin", "Osla"]),
    dict(name="Nag Tibba Trek", titles=["Nag Tibba"], district="Dehradun", region="Garhwal",
         location="Near Mussoorie / Pantwari", category="Trekking", search_ctx="Nag Tibba peak Uttarakhand",
         highlight_candidates=["Nag Devta", "Black Mountain"]),
    dict(name="Dayara Bugyal Trek", titles=["Dayara Bugyal"], district="Uttarkashi", region="Garhwal",
         location="Raithal / Barsu, Uttarkashi", category="Trekking", search_ctx="Dayara Bugyal Uttarakhand",
         highlight_categories=None, highlight_candidates=["Gidara", "Barnala Tal"]),
    dict(name="Dodital Trek", titles=["Dodital", "Dodital Lake"], district="Uttarkashi", region="Garhwal",
         location="Near Sangam Chatti / Darwa", category="Trekking", search_ctx="Dodital lake Uttarakhand",
         highlight_candidates=["Ganesha", "trout", "Darwa Pass"]),
    dict(name="Kedartal Trek", titles=["Kedartal"], district="Uttarkashi", region="Garhwal",
         location="Near Gangotri", category="Trekking", search_ctx="Kedartal lake Gangotri",
         highlight_candidates=["Thalay Sagar", "Bhrigupanth"]),
    dict(name="Gaumukh–Tapovan Trek", titles=["Gangotri Glacier"], district="Uttarkashi", region="Garhwal",
         location="Gangotri to Gaumukh", category="Trekking", search_ctx="Gangotri glacier Gaumukh Tapovan",
         highlight_candidates=["Gaumukh", "Tapovan", "Bhagirathi", "Shivling"]),
    dict(name="Deoria Tal Trek", titles=["Deoria Tal"], district="Rudraprayag", region="Garhwal",
         location="Sari village, near Ukhimath", category="Trekking", search_ctx="Deoria Tal lake Uttarakhand",
         highlight_candidates=["Chaukhamba", "Ukhimath"]),
    dict(name="Pindari Glacier Trek", titles=["Pindari Glacier"], district="Bageshwar", region="Kumaon",
         location="Loharkhet / Khati, Bageshwar", category="Trekking", search_ctx="Pindari glacier Uttarakhand",
         highlight_candidates=["Kafni", "Zero Point", "Khati"]),
    dict(name="Milam Glacier Trek", titles=["Milam Glacier"], district="Pithoragarh", region="Kumaon",
         location="Munsiyari", category="Trekking", search_ctx="Milam glacier Uttarakhand Munsiyari",
         highlight_candidates=["Johar valley", "Milam village", "Nanda Devi"]),
    dict(name="Kempty Falls Visit", titles=["Kempty Falls"], district="Tehri Garhwal", region="Garhwal",
         location="13 km from Mussoorie", category="Waterfalls & Sightseeing", search_ctx="Kempty Falls Mussoorie",
         highlight_candidates=["Mussoorie", "Chakrata Road"]),
    dict(name="Nanda Devi Raj Jat", titles=["Nanda Devi Raj Jat"], district="Chamoli", region="Garhwal",
         location="Nauti to Roopkund (Chamoli)", category="Pilgrimage / Festival", search_ctx="Nanda Devi Raj Jat yatra Uttarakhand",
         extra_tokens=["roopkund", "bedni", "nauti"],
         highlight_candidates=["Roopkund", "Himalayan Mahakumbh", "Nauti", "Kuari Pass"]),
    dict(name="Chandrashila Trek", titles=["Chandrashila"], district="Rudraprayag", region="Garhwal",
         location="Above Tungnath, near Chopta", category="Trekking", search_ctx="Chandrashila peak Tungnath",
         extra_tokens=["chandrasila"],
         highlight_candidates=["Tungnath", "Nanda Devi", "Trishul", "Kedarnath"]),
    dict(name="Chota Char Dham Yatra", titles=["Chota Char Dham"], district="Multiple (Uttarakhand)", region="Garhwal",
         location="Yamunotri, Gangotri, Kedarnath, Badrinath", category="Pilgrimage", search_ctx="Char Dham Uttarakhand yatra",
         extra_tokens=["yamunotri", "gangotri", "kedarnath", "badrinath"],
         highlight_candidates=["Yamunotri", "Gangotri", "Kedarnath", "Badrinath", "Adi Shankara"]),
    dict(name="Bungee Jumping at Mohan Chatti", titles=[], wikivoyage="Rishikesh", district="Dehradun", region="Garhwal",
         location="Mohan Chatti, near Rishikesh", category="Adventure Sports", search_ctx="bungee jumping Mohan Chatti Rishikesh",
         extra_tokens=["bungee"],
         highlight_candidates=["bungee", "flying fox", "giant swing"]),
    dict(name="Skiing in Auli", titles=["Auli, India"], district="Chamoli", region="Garhwal",
         location="Auli, near Joshimath", category="Skiing", search_ctx="Auli skiing slopes Uttarakhand",
         extra_tokens=["ski"],
         highlight_candidates=["ropeway", "Gurso Bugyal", "artificial lake"]),
    dict(name="Boating on Naini Lake", titles=["Naini Lake"], district="Nainital", region="Kumaon",
         location="Nainital", category="Boating", search_ctx="Naini Lake Nainital boating",
         extra_tokens=["nainital", "boat"],
         highlight_candidates=["yachting", "Balia Tal"]),
    dict(name="Jeep Safari in Jim Corbett National Park", titles=["Jim Corbett National Park"], district="Nainital", region="Garhwal",
         location="Ramnagar", category="Wildlife Safari", search_ctx="Jim Corbett National Park safari tiger",
         extra_tokens=["corbett", "tiger", "safari"],
         highlight_candidates=["Bengal tiger", "Dhikala", "Bijrani", "Jhirna"]),
    dict(name="Wildlife Safari in Rajaji National Park", titles=["Rajaji National Park"], district="Haridwar", region="Garhwal",
         location="Haridwar–Dehradun range", category="Wildlife Safari", search_ctx="Rajaji National Park safari elephant",
         extra_tokens=["rajaji", "elephant"],
         highlight_candidates=["elephant", "tiger", "Chilla"]),
    dict(name="White-Water Rafting in Rishikesh", titles=[], wikivoyage="Rishikesh", district="Dehradun", region="Garhwal",
         location="Rishikesh (Brahmapuri–Shivpuri stretch)", category="River Rafting", search_ctx="rafting Ganga Rishikesh",
         extra_tokens=["rafting", "kaudiyala", "shivpuri"],
         highlight_candidates=["Shivpuri", "Marine Drive", "Grade"]),
]


# ---------------------------------------------------------------- EXPANSION BATCH 1
# Added 2026-09-11 from Wikipedia category mining (Tourist attractions in
# Uttarakhand tree, hill stations, valleys, passes, protected areas, temples,
# museums, festivals, hiking trails). 97 entities. Districts to be audited
# against Wikidata P131 post-collection.

DESTINATIONS += [
    # --- Garhwal towns / confluences / bases ---
    dict(name="Landour", titles=["Landour"], district="Dehradun", region="Garhwal",
         search_ctx="Landour Mussoorie cantonment",
         highlight_candidates=["Lal Tibba", "Char Dukan", "Kellogg's Church", "cantonment"]),
    dict(name="Kotdwar", titles=["Kotdwar", "Kotdwara"], district="Pauri Garhwal", region="Garhwal",
         search_ctx="Kotdwar Uttarakhand gateway",
         highlight_candidates=["Sidhbali Temple", "Kanvashram", "Khoh"]),
    dict(name="Pauri", titles=["Pauri"], district="Pauri Garhwal", region="Garhwal",
         search_ctx="Pauri Uttarakhand hill town",
         highlight_candidates=["Kandoliya", "Kyunkaleshwar Temple", "Nagdev"]),
    dict(name="Srinagar", titles=["Srinagar, Uttarakhand"], district="Pauri Garhwal", region="Garhwal",
         search_ctx="Srinagar Garhwal Alaknanda town",
         highlight_candidates=["Dhari Devi", "Alaknanda", "Hemwati Nandan Bahuguna"]),
    dict(name="Devprayag", titles=["Devprayag"], district="Pauri Garhwal", region="Garhwal",
         search_ctx="Devprayag confluence Bhagirathi Alaknanda",
         highlight_candidates=["Bhagirathi", "Alaknanda", "Raghunath"]),
    dict(name="Karnaprayag", titles=["Karnaprayag"], district="Chamoli", region="Garhwal",
         search_ctx="Karnaprayag confluence Pindar Alaknanda",
         highlight_candidates=["Pindar", "Alaknanda", "Karna"]),
    dict(name="Nandaprayag", titles=["Nandaprayag"], district="Chamoli", region="Garhwal",
         search_ctx="Nandaprayag confluence Uttarakhand",
         highlight_candidates=["Nandakini", "Alaknanda"]),
    dict(name="Vishnuprayag", titles=["Vishnuprayag"], district="Chamoli", region="Garhwal",
         search_ctx="Vishnuprayag confluence Dhauliganga",
         highlight_candidates=["Dhauliganga", "Alaknanda", "Badri"]),
    dict(name="Sonprayag", titles=["Sonprayag"], district="Rudraprayag", region="Garhwal",
         search_ctx="Sonprayag Kedarnath route",
         highlight_candidates=["Kedarnath", "Mandakini"]),
    dict(name="Gopeshwar", titles=["Chamoli Gopeshwar", "Gopeshwar"], district="Chamoli", region="Garhwal",
         search_ctx="Gopeshwar Chamoli town",
         highlight_candidates=["Gopinath Temple", "Auli", "Trishul"]),
    dict(name="Govindghat", titles=["Govindghat"], district="Chamoli", region="Garhwal",
         search_ctx="Govindghat Valley of Flowers Hemkund ghat",
         highlight_candidates=["Valley of Flowers", "Hemkund", "Lakshman Ganga"]),
    dict(name="Mana", titles=["Mana, Chamoli"], district="Chamoli", region="Garhwal",
         search_ctx="Mana village last India Tibet border",
         highlight_candidates=["Vyas Gufa", "Bhim Pul", "Saraswati"]),
    dict(name="Ghangaria", titles=["Ghangaria"], district="Chamoli", region="Garhwal",
         search_ctx="Ghangaria Hemkund Valley of Flowers base",
         highlight_candidates=["Hemkund", "Valley of Flowers", "Pushpawati"]),
    dict(name="Sankri", titles=["Sankri"], district="Uttarkashi", region="Garhwal",
         search_ctx="Sankri village Har Ki Dun Kedarkantha",
         highlight_candidates=["Har Ki Dun", "Kedarkantha", "Swargarohini"]),
    dict(name="Barkot", titles=["Barkot, Uttarakhand"], district="Uttarkashi", region="Garhwal",
         search_ctx="Barkot Yamunotri Uttarakhand",
         highlight_candidates=["Yamunotri", "Barkot"]),
    dict(name="Chamba", titles=["Chamba, Uttarakhand"], district="Tehri Garhwal", region="Garhwal",
         search_ctx="Chamba Tehri Uttarakhand town",
         highlight_candidates=["Tehri Dam", "Surkanda Devi", "Bhagirathi"]),
    dict(name="Tehri Dam", titles=["Tehri Dam"], district="Tehri Garhwal", region="Garhwal",
         search_ctx="Tehri Dam lake Uttarakhand",
         highlight_candidates=["Tehri Lake", "Bhagirathi", "Bhilangana"]),
    dict(name="Gaumukh", titles=["Gomukh", "Gangotri Glacier"], district="Uttarkashi", region="Garhwal",
         search_ctx="Gaumukh Gangotri glacier snout source of Ganges",
         highlight_candidates=["Gangotri Glacier", "Bhagirathi", "source"]),
    dict(name="Vasudhara Falls", titles=["Vasudhara Falls"], district="Chamoli", region="Garhwal",
         search_ctx="Vasudhara Falls Badrinath Uttarakhand",
         highlight_candidates=["Badrinath", "Alaknanda"]),
    dict(name="Bedni Bugyal", titles=["Bedni Bugyal"], district="Chamoli", region="Garhwal",
         search_ctx="Bedni Bugyal meadow Roopkund",
         highlight_candidates=["Roopkund", "Nanda Devi Raj Jat", "Ali Bugyal"]),
    dict(name="Panwali Kantha Bugyal", titles=["Panwali Kantha Bugyal", "Panwali Kantha"], district="Tehri Garhwal", region="Garhwal",
         search_ctx="Panwali Kantha bugyal meadow Uttarakhand",
         highlight_candidates=["bugyal", "Ghuttu"]),
    dict(name="Gangotri National Park", titles=["Gangotri National Park"], district="Uttarkashi", region="Garhwal",
         search_ctx="Gangotri National Park Uttarakhand",
         highlight_candidates=["Gaumukh", "snow leopard", "bharal"]),
    dict(name="Govind Pashu Vihar National Park", titles=["Govind Pashu Vihar National Park", "Govind Pashu Vihar"], district="Uttarkashi", region="Garhwal",
         search_ctx="Govind Pashu Vihar National Park Har Ki Dun",
         highlight_candidates=["Har Ki Dun", "snow leopard", "black bear"]),
    dict(name="Nanda Devi National Park", titles=["Nanda Devi National Park"], district="Chamoli", region="Garhwal",
         search_ctx="Nanda Devi National Park UNESCO",
         highlight_candidates=["UNESCO", "Nanda Devi", "Rishi Ganga"]),
    dict(name="Askot Musk Deer Sanctuary", titles=["Askot Musk Deer Sanctuary"], district="Pithoragarh", region="Kumaon",
         search_ctx="Askot Musk Deer Sanctuary Pithoragarh",
         highlight_candidates=["musk deer"]),
    dict(name="Kedarnath Wildlife Sanctuary", titles=["Kedarnath Wildlife Sanctuary", "Kedarnath Musk Deer Sanctuary"], district="Rudraprayag", region="Garhwal",
         search_ctx="Kedarnath Wildlife Sanctuary Uttarakhand",
         highlight_candidates=["musk deer", "Kedarnath", "monal"]),
    dict(name="Asan Barrage", titles=["Asan Barrage"], district="Dehradun", region="Garhwal",
         search_ctx="Asan Barrage wetland birds Dehradun",
         highlight_candidates=["migratory", "Yamuna", "birdwatching"]),
    # --- Kumaon towns / hill stations ---
    dict(name="Haldwani", titles=["Haldwani"], district="Nainital", region="Kumaon",
         search_ctx="Haldwani gateway Kumaon Uttarakhand",
         highlight_candidates=["gateway", "Kumaon", "Gaula"]),
    dict(name="Kaladhungi", titles=["Kaladhungi"], district="Nainital", region="Kumaon",
         search_ctx="Kaladhungi Jim Corbett Chhoti Haldwani",
         highlight_candidates=["Jim Corbett", "Chhoti Haldwani", "Corbett Museum"]),
    dict(name="Dhanachuli", titles=["Dhanachuli"], district="Nainital", region="Kumaon",
         search_ctx="Dhanachuli village Nainital Himalayas",
         highlight_candidates=["Himalaya", "village"]),
    dict(name="Pangot", titles=["Pangot"], district="Nainital", region="Kumaon",
         search_ctx="Pangot Kilbury birding Nainital",
         highlight_candidates=["Kilbury", "bird"]),
    dict(name="Ramgarh", titles=["Ramgarh, Uttarakhand"], district="Nainital", region="Kumaon",
         search_ctx="Ramgarh orchards Nainital Kumaon",
         highlight_candidates=["orchard", "Nathuakhan", "Tagore"]),
    dict(name="Bhowali", titles=["Bhowali"], district="Nainital", region="Kumaon",
         search_ctx="Bhowali Uttarakhand town",
         highlight_candidates=["Ghorakhal", "Sattal"]),
    dict(name="Jeolikot", titles=["Jeolikot", "Jeolikote"], district="Nainital", region="Kumaon",
         search_ctx="Jeolikot Nainital butterflies",
         highlight_candidates=["butterfl", "Nainital"]),
    dict(name="Vijaypur", titles=["Vijaypur, Uttarakhand"], district="Bageshwar", region="Kumaon",
         search_ctx="Vijaypur Bageshwar Kausani viewpoint",
         highlight_candidates=["Kausani", "Himalaya"]),
    dict(name="Someshwar", titles=["Someshwar, Uttarakhand"], district="Almora", region="Kumaon",
         search_ctx="Someshwar valley Almora Uttarakhand",
         highlight_candidates=["Someshwar", "valley"]),
    dict(name="Chaukhutia", titles=["Chaukhutia"], district="Almora", region="Kumaon",
         search_ctx="Chaukhutia Almora Kali river",
         highlight_candidates=["Kali", "ruins"]),
    dict(name="Berinag", titles=["Berinag"], district="Pithoragarh", region="Kumaon",
         search_ctx="Berinag Pithoragarh hill station tea",
         highlight_candidates=["tea", "Himalaya"]),
    dict(name="Didihat", titles=["Didihat"], district="Pithoragarh", region="Kumaon",
         search_ctx="Didihat Pithoragarh Uttarakhand",
         highlight_candidates=["Panchachuli", "Himalaya"]),
    dict(name="Dharchula", titles=["Dharchula"], district="Pithoragarh", region="Kumaon",
         search_ctx="Dharchula Kali river Nepal border",
         highlight_candidates=["Kali River", "Nepal", "Kailash"]),
    dict(name="Gangolihat", titles=["Gangolihat"], district="Pithoragarh", region="Kumaon",
         search_ctx="Gangolihat Haat Kalika Patal Bhuvaneshwar",
         highlight_candidates=["Kali", "Patal Bhuvaneshwar"]),
    dict(name="Champawat", titles=["Champawat"], district="Champawat", region="Kumaon",
         search_ctx="Champawat Uttarakhand Katyuri historic town",
         highlight_candidates=["Baleshwar", "Katyuri", "Chand"]),
    dict(name="Darma Valley", titles=["Darma Valley", "Darma valley"], district="Pithoragarh", region="Kumaon",
         search_ctx="Darma Valley Pithoragarh trek",
         highlight_candidates=["Darma", "Om Parvat", "tribal"]),
    dict(name="Johar Valley", titles=["Johar Valley", "Johar valley"], district="Pithoragarh", region="Kumaon",
         search_ctx="Johar Valley Munsiyari Milam glacier",
         highlight_candidates=["Milam", "Munsiyari", "Gori"]),
    dict(name="Niti Valley", titles=["Niti Valley"], district="Chamoli", region="Garhwal",
         search_ctx="Niti Valley Chamoli Malari border",
         highlight_candidates=["Malari", "Niti", "Dhauliganga"]),
]

SPIRITUAL += [
    dict(name="Triyuginarayan Temple", titles=["Triyuginarayan Temple", "Triyuginarayan"], district="Rudraprayag", region="Garhwal",
         location="Sonprayag–Guptakashi area", search_ctx="Triyuginarayan temple wedding Shiva Parvati",
         highlight_candidates=["wedding", "Shiva", "Parvati", "Agni", "eternal flame"]),
    dict(name="Kalimath", titles=["Kalimath"], district="Rudraprayag", region="Garhwal",
         location="Near Guptakashi", search_ctx="Kalimath temple Kali Rudraprayag",
         highlight_candidates=["Kali", "Saraswati", "Lakshmi"]),
    dict(name="Koteshwar Mahadev Temple", titles=["Koteshwar Mahadev"], district="Rudraprayag", region="Garhwal",
         location="Rudraprayag, Alaknanda bank", search_ctx="Koteshwar Mahadev cave temple Rudraprayag",
         highlight_candidates=["cave", "Alaknanda", "Shiva"]),
    dict(name="Gauri Kund", titles=["Gauri Kund"], district="Rudraprayag", region="Garhwal",
         location="Base of Kedarnath trek", search_ctx="Gauri Kund temple hot spring Kedarnath",
         highlight_candidates=["Kedarnath", "Parvati", "hot spring"]),
    dict(name="Chandrabadani Devi", titles=["Chandrabadani Devi", "Chandrabadani"], district="Tehri Garhwal", region="Garhwal",
         location="Chandrabadani hill, Tehri–Devprayag road", search_ctx="Chandrabadani Devi temple Tehri",
         highlight_candidates=["Sati", "goddess", "Shakti Peeth"]),
    dict(name="Jwalpa Devi Temple", titles=["Jwalpa Devi"], district="Pauri Garhwal", region="Garhwal",
         location="Near Pauri", search_ctx="Jwalpa Devi temple Pauri Garhwal",
         highlight_candidates=["Durga", "goddess"]),
    dict(name="Raghunath Temple, Devprayag", titles=["Raghunath Temple, Devprayag"], district="Pauri Garhwal", region="Garhwal",
         location="Devprayag", search_ctx="Raghunath temple Devprayag Rama",
         highlight_candidates=["Rama", "confluence", "Bhagirathi"]),
    dict(name="Mahasu Devta Temple", titles=["Mahasu Devta Temple", "Mahasu Devta"], district="Dehradun", region="Garhwal",
         location="Hanol, Jaunsar-Bawar", search_ctx="Mahasu Devta temple Hanol",
         highlight_candidates=["Hanol", "Mahasu", "deity"]),
    dict(name="Lakhamandal", titles=["Lakhamandal"], district="Dehradun", region="Garhwal",
         location="Jaunsar-Bawar, near Mussoorie–Chakrata", search_ctx="Lakhamandal temple Mahabharata Pandavas",
         highlight_candidates=["Mahabharata", "Pandavas", "Shiva", "Kauravas"]),
    dict(name="Beatles Ashram", titles=["Beatles Ashram", "Chaurasi Kutia"], district="Dehradun", region="Garhwal",
         location="Rishikesh", search_ctx="Beatles Ashram Maharishi Rishikesh Chaurasi Kutia",
         highlight_candidates=["Maharishi", "Beatles", "Transcendental Meditation"]),
    dict(name="Divine Life Society", titles=["Divine Life Society"], district="Dehradun", region="Garhwal",
         location="Rishikesh", search_ctx="Divine Life Society Sivananda Ashram Rishikesh",
         highlight_candidates=["Sivananda", "Rishikesh", "yoga"]),
    dict(name="Mindrolling Monastery", titles=["Clement Town"], district="Dehradun", region="Garhwal",
         location="Clement Town, Dehradun", search_ctx="Mindrolling Monastery Great Stupa Clement Town Dehradun",
         highlight_candidates=["Nyingma", "stupa", "Tibetan"]),
    dict(name="Guru Ram Rai Darbar Sahib", titles=["Guru Ram Rai Darbar Sahib"], district="Dehradun", region="Garhwal",
         location="Dehradun", search_ctx="Guru Ram Rai Darbar Sahib gurdwara Dehradun",
         highlight_candidates=["Guru Ram Rai", "Dehradun", "Sikh"]),
    dict(name="Jyotir Math", titles=["Jyotir Math"], district="Chamoli", region="Garhwal",
         location="Joshimath", search_ctx="Jyotir Math Joshimath Shankaracharya",
         highlight_candidates=["Shankaracharya", "Badri", "matha"]),
    dict(name="Gopinath Temple, Gopeshwar", titles=["Gopinath Temple, Gopeshwar"], district="Chamoli", region="Garhwal",
         location="Gopeshwar", search_ctx="Gopinath temple Gopeshwar trishul",
         highlight_candidates=["trishul", "Gopeshwar", "Shiva"]),
    dict(name="Adi Badri", titles=["Adi Badri"], district="Chamoli", region="Garhwal",
         location="Karnaprayag area", search_ctx="Adi Badri temple Sapta Badri",
         highlight_candidates=["Sapta Badri", "Vishnu", "Gupta"]),
    dict(name="Binsar Mahadev Temple", titles=["Binsar Mahadev"], district="Pauri Garhwal", region="Garhwal",
         location="Bisaona village, Thalisain, Pauri Garhwal", search_ctx="Binsar Mahadev temple Pauri Garhwal Bisaona",
         highlight_candidates=["Ranikhet", "Shiva"]),
    dict(name="Bagnath Temple", titles=["Bagnath Temple"], district="Bageshwar", region="Kumaon",
         location="Bageshwar", search_ctx="Bagnath temple Bageshwar Shiva Sarayu",
         highlight_candidates=["Shiva", "Sarayu", "Bageshwar"]),
    dict(name="Garjiya Devi Temple", titles=["Garjiya Devi"], district="Nainital", region="Kumaon",
         location="Ramnagar, near Corbett", search_ctx="Garjiya Devi temple Ramnagar Corbett",
         highlight_candidates=["Corbett", "Kosi", "goddess"]),
    dict(name="Ghorakhal", titles=["Ghorakhal"], district="Nainital", region="Kumaon",
         location="Near Bhowali", search_ctx="Ghorakhal Golu Devta temple Sainik School",
         highlight_candidates=["Golu Devta", "Sainik School"]),
    dict(name="Hanumangarhi, Nainital", titles=["Hanumangarhi, Nainital"], district="Nainital", region="Kumaon",
         location="Nainital", search_ctx="Hanumangarhi temple Nainital Hanuman hill",
         highlight_candidates=["Hanuman", "sunset"]),
    dict(name="Nanakmatta", titles=["Nanakmatta"], district="Udham Singh Nagar", region="Kumaon",
         location="Near Khatima–Sitarganj", search_ctx="Nanakmatta gurdwara Guru Nanak Udham Singh Nagar",
         highlight_candidates=["Guru Nanak", "gurdwara", "Sikh"]),
    dict(name="Baleshwar Temple", titles=["Baleshwar Temple"], district="Champawat", region="Kumaon",
         location="Champawat", search_ctx="Baleshwar temple Champawat Katyuri Shiva",
         highlight_candidates=["Katyuri", "Shiva", "Champawat"]),
    dict(name="Gurdwara Gyan Godri Sahib", titles=["Gurdwara Gyan Godri Sahib"], district="Haridwar", region="Garhwal",
         location="Har Ki Pauri, Haridwar", search_ctx="Gyan Godri gurdwara Haridwar Guru Nanak",
         highlight_candidates=["Guru Nanak", "Har Ki Pauri", "Ganga"]),
    dict(name="Daksheswar Mahadev Temple", titles=["Daksheswar Mahadev Temple", "Daksha Mahadev temple"], district="Haridwar", region="Garhwal",
         location="Kankhal, Haridwar", search_ctx="Daksheswar Mahadev temple Kankhal Sati",
         highlight_candidates=["Daksha", "Sati", "Kankhal"]),
    dict(name="Satopanth Tal", titles=["Satopanth Tal"], district="Chamoli", region="Garhwal",
         location="Above Badrinath", search_ctx="Satopanth Tal sacred lake Badrinath",
         highlight_candidates=["Chaukhamba", "Brahma", "Vishnu", "Mahesh"]),
]

CULTURAL += [
    dict(name="Haridwar Kumbh Mela", titles=["Haridwar Kumbh Mela", "Kumbh Mela"], district="Haridwar", region="Garhwal",
         location="Har Ki Pauri, Haridwar", search_ctx="Kumbh Mela Haridwar Har Ki Pauri",
         highlight_candidates=["Har Ki Pauri", "Ganga", "millions", "pilgrims"]),
    dict(name="Kanwar Yatra", titles=["Kanwar Yatra"], district="Haridwar", region="Garhwal",
         location="Haridwar–Ganga canal route", search_ctx="Kanwar Yatra Haridwar Ganga devotees",
         highlight_candidates=["Ganga", "Shiva", "kanwar"]),
    dict(name="Harela", titles=["Harela"], district="Multiple (Uttarakhand)", region="Kumaon",
         location="Uttarakhand (Kumaon)", search_ctx="Harela festival Uttarakhand greenery",
         highlight_candidates=["seeds", "green", "monsoon", "festival"]),
    dict(name="Igas Bagwal", titles=["Igas Bagwal"], district="Multiple (Uttarakhand)", region="Garhwal",
         location="Garhwal", search_ctx="Igas Bagwal festival Garhwal Diwali",
         highlight_candidates=["Diwali", "Pandavas", "fire"]),
    dict(name="Kandali Festival", titles=["Kandali Festival"], district="Pithoragarh", region="Kumaon",
         location="Darma/Johar valleys, Pithoragarh", search_ctx="Kandali festival Pithoragarh Rang community",
         highlight_candidates=["Rang", "buckwheat", "twelve"]),
    dict(name="Kumaoni Holi", titles=["Kumaoni Holi"], district="Multiple (Uttarakhand)", region="Kumaon",
         location="Kumaon", search_ctx="Kumaoni Holi Baithki Khari Holi songs",
         highlight_candidates=["Baithki", "Khari", "Mahila", "songs"]),
    dict(name="Pandav Lila", titles=["Pandav Lila"], district="Multiple (Uttarakhand)", region="Garhwal",
         location="Garhwal villages", search_ctx="Pandav Lila folk theatre Garhwal Mahabharata",
         highlight_candidates=["Pandavas", "Mahabharata", "drum", "dance"]),
    dict(name="Ramman", titles=["Ramman (festival)"], district="Chamoli", region="Garhwal",
         location="Saloor–Dungra villages, Chamoli", search_ctx="Ramman festival UNESCO Saloor Dungra Chamoli",
         highlight_candidates=["UNESCO", "Saloor", "Dungra", "Bhumiyal"]),
    dict(name="Virasat", titles=["Virasat (festival)"], district="Dehradun", region="Garhwal",
         location="Dehradun", search_ctx="Virasat festival Dehradun heritage arts",
         highlight_candidates=["heritage", "arts", "festival"]),
    dict(name="Chholiya", titles=["Chholiya"], district="Multiple (Uttarakhand)", region="Kumaon",
         location="Kumaon", search_ctx="Chholiya sword dance Kumaon wedding",
         highlight_candidates=["sword", "wedding", "dance", "Kumaon"]),
    dict(name="Jagar", titles=["Jagar (ritual)"], district="Multiple (Uttarakhand)", region="Garhwal",
         location="Garhwal–Kumaon", search_ctx="Jagar ritual Uttarakhand spirit possession folk",
         highlight_candidates=["possession", "spirits", "ritual", "night"]),
    dict(name="Kumaoni cuisine", titles=["Kumaoni cuisine"], district="Multiple (Uttarakhand)", region="Kumaon",
         location="Kumaon", search_ctx="Kumaoni cuisine bal mithai bhatt dubka",
         highlight_candidates=["Bal mithai", "bhatt", "Dubka", "Jholi", "buckwheat"]),
    dict(name="Bal mithai", titles=["Bal mithai"], district="Almora", region="Kumaon",
         location="Almora", search_ctx="Bal mithai sweet Almora Kumaon khoya",
         highlight_candidates=["khoya", "Almora", "sweet", "poppy"]),
    dict(name="Lakhudiyar Caves", titles=["Lakhudiyar Caves"], district="Almora", region="Kumaon",
         location="Almora", search_ctx="Lakhudiyar caves rock paintings Almora",
         highlight_candidates=["rock", "paintings", "prehistoric"]),
    dict(name="Rock Edicts of Khalsi", titles=["Rock edicts of Khalsi", "Kalsi"], district="Dehradun", region="Garhwal",
         location="Kalsi, Dehradun", search_ctx="Kalsi rock edicts Ashoka Dehradun",
         highlight_candidates=["Ashoka", "edicts", "Mauryan"]),
    dict(name="Khalanga War Memorial", titles=["Khalanga War Memorial"], district="Dehradun", region="Garhwal",
         location="Dehradun", search_ctx="Khalanga War Memorial Anglo Nepalese Nalapani Dehradun",
         highlight_candidates=["Nalapani", "Gurkha", "Anglo-Nepalese", "Balbhadra"]),
    dict(name="St. Paul's Church, Landour", titles=["St. Paul's Church, Landour"], district="Dehradun", region="Garhwal",
         location="Landour, Mussoorie", search_ctx="St Paul's Church Landour Mussoorie",
         highlight_candidates=["Landour", "church", "British"]),
    dict(name="Kipling Trail", titles=["Kipling Trail"], district="Dehradun", region="Garhwal",
         location="Mussoorie–Landour", search_ctx="Kipling Trail Mussoorie Landour walk",
         highlight_candidates=["Kipling", "Landour", "walk"]),
    dict(name="Cranks' Ridge", titles=["Cranks' Ridge"], district="Almora", region="Kumaon",
         location="Kasar Devi, Almora", search_ctx="Cranks Ridge Kasar Devi Almora hippie",
         highlight_candidates=["Kasar Devi", "hippie", "Lawrence", "sunrise"]),
    dict(name="Hindu Genealogy Registers at Haridwar", titles=["Hindu genealogy registers at Haridwar"], district="Haridwar", region="Garhwal",
         location="Haridwar", search_ctx="Haridwar genealogy registers pandas Brahmin records",
         highlight_candidates=["pandas", "registers", "ancestors", "pilgrims"]),
]

ACTIVITIES += [
    dict(name="Kedarkantha Trek", titles=["Kedarkantha"], district="Uttarkashi", region="Garhwal",
         location="Sankri, Uttarkashi", category="Trekking", search_ctx="Kedarkantha trek winter snow Sankri",
         highlight_candidates=["Swargarohini", "snow", "winter", "summit"]),
    dict(name="Kafni Glacier Trek", titles=["Kafni Glacier"], district="Bageshwar", region="Kumaon",
         location="Loharkhet–Dhakuri route, Bageshwar", category="Trekking", search_ctx="Kafni Glacier trek Pindari Nanda Khat",
         highlight_candidates=["Nanda Khat", "Pindari", "glacier"]),
    dict(name="Khatling Glacier Trek", titles=["Khatling Glacier"], district="Tehri Garhwal", region="Garhwal",
         location="Ghuttu, Tehri Garhwal", category="Trekking", search_ctx="Khatling Glacier trek Bhilangna Sahasratal",
         highlight_candidates=["Bhilangna", "Sahasratal", "glacier"]),
    dict(name="Satopanth Tal Trek", titles=["Satopanth Tal"], district="Chamoli", region="Garhwal",
         location="Above Badrinath", category="Trekking", search_ctx="Satopanth Tal trek Badrinath Chaukhamba",
         highlight_candidates=["Chaukhamba", "Brahma", "Vishnu", "Mahesh"]),
    dict(name="Panch Kedar Yatra", titles=["Panch Kedar"], district="Multiple (Uttarakhand)", region="Garhwal",
         location="Garhwal (Rudraprayag–Chamoli–Almora)", category="Pilgrimage", search_ctx="Panch Kedar yatra five Shiva temples",
         highlight_candidates=["Kedarnath", "Tungnath", "Rudranath", "Madhyamaheshwar", "Kalpeshwar"]),
]


# ---------------------------------------------------------------- EXPANSION BATCH 2 (TripAdvisor gap-fill)
# Added 2026-09-12 after comparing our coverage against TripAdvisor's
# "30 BEST Things to Do in Uttarakhand" (top-12: 10/12 already covered) and
# their popular-tour destinations. All 11 entities are Wikipedia-documented.
# Known gaps NOT added (no permitted-source documentation): Vashishta Gufa
# (TA #6), Kunjapuri Temple, Corbett Falls, Gartang Gali, Jhilmil Jheel,
# Naina Devi Temple Nainital, Neer Garh Falls, Snow View Point.

DESTINATIONS += [
    dict(name="Om Parvat", titles=["Om Parvat"], district="Pithoragarh", region="Kumaon",
         search_ctx="Om Parvat sacred mountain snow Om",
         highlight_candidates=["Kailash", "Mansarovar", "Om", "snow"]),
    dict(name="Adi Kailash", titles=["Adi Kailash"], district="Pithoragarh", region="Kumaon",
         search_ctx="Adi Kailash Chhota Kailash mountain",
         highlight_candidates=["Kailash", "Brahma", "Parvati", "trek", "Om Parvat"]),
    dict(name="Kuthi Valley", titles=["Kuthi Valley"], district="Pithoragarh", region="Kumaon",
         search_ctx="Kuthi Valley Pithoragarh Kuti river",
         highlight_candidates=["Kuti", "Tibet", "trade", "glacier"]),
    dict(name="Dunagiri", titles=["Dunagiri"], district="Almora", region="Kumaon",
         search_ctx="Dunagiri temple hill Almora",
         highlight_candidates=["Dunagiri Temple", "Babaji", "cave", "Pandavkholi"]),
    dict(name="Binsar Wildlife Sanctuary", titles=["Binsar Wildlife Sanctuary"], district="Almora", region="Kumaon",
         search_ctx="Binsar Wildlife Sanctuary zero point",
         highlight_candidates=["Zero Point", "oak", "leopard", "barking deer"]),
    dict(name="Panchachuli", titles=["Panchachuli"], district="Pithoragarh", region="Kumaon",
         search_ctx="Panchachuli peaks massif Dharchula",
         highlight_candidates=["five peaks", "Darma", "glacier", "Milam"]),
    dict(name="Tiger Falls", titles=["Tiger Falls"], district="Dehradun", region="Garhwal",
         search_ctx="Tiger Falls Chakrata waterfall Uttarakhand",
         highlight_candidates=["Chakrata", "waterfall", "cascade"]),
    dict(name="Robber's Cave", titles=["Robber's Cave, India"], district="Dehradun", region="Garhwal",
         search_ctx="Robber's Cave Gucchupani Dehradun",
         highlight_candidates=["Gucchupani", "riverine cave", "Dehradun"]),
]

SPIRITUAL += []

CULTURAL += [
    dict(name="Lakshman Jhula", titles=["Lakshman Jhula"], district="Dehradun", region="Garhwal",
         location="Rishikesh, across the Ganges", search_ctx="Lakshman Jhula bridge Rishikesh",
         highlight_candidates=["suspension bridge", "Laxman", "Ganga", "1929", "Tera Manzil"]),
    dict(name="Ram Jhula", titles=["Ram Jhula"], district="Dehradun", region="Garhwal",
         location="Rishikesh, across the Ganges", search_ctx="Ram Jhula bridge Rishikesh Sivananda",
         highlight_candidates=["suspension bridge", "Sivananda", "Ganga", "Geeta Bhawan"]),
    dict(name="Winterline", titles=["Winterline"], district="Dehradun", region="Garhwal",
         location="Mussoorie", search_ctx="Winterline Mussoorie horizon phenomenon",
         highlight_candidates=["horizon", "sunset", "phenomenon", "carnival"]),
]

ACTIVITIES += []
