#!/usr/bin/env python3
"""Append EXPANSION BATCH 1 (97 new entities) to scripts/config.py.
All entities are Wikipedia-documented places/sites/events verified via
category mining (raw/_wiki_candidates.json) on 2026-09-11.
District assignments are curated and will be cross-audited against
Wikidata P131 after collection."""

import io, re

PATCH = '''

# ---------------------------------------------------------------- EXPANSION BATCH 1
# Added 2026-09-11 from Wikipedia category mining (Tourist attractions in
# Uttarakhand tree, hill stations, valleys, passes, protected areas, temples,
# museums, festivals, hiking trails). 97 entities. Districts to be audited
# against Wikidata P131 post-collection.

DESTINATIONS += [
    # --- Garhwal towns / confluences / bases ---
    dict(name="Landour", titles=["Landour"], district="Dehradun", region="Garhwal",
         search_ctx="Landour Mussoorie cantonment",
         highlight_candidates=["Lal Tibba", "Char Dukan", "Kellogg's Church", "cantonment"]),
    dict(name="Kotdwar", titles=["Kotdwar", "Kotdwara"], district="Pauri Garhwal", region="Garhwal",
         search_ctx="Kotdwar Uttarakhand gateway",
         highlight_candidates=["Sidhbali Temple", "Kanvashram", "Khoh"]),
    dict(name="Pauri", titles=["Pauri"], district="Pauri Garhwal", region="Garhwal",
         search_ctx="Pauri Uttarakhand hill town",
         highlight_candidates=["Kandoliya", "Kyunkaleshwar Temple", "Nagdev"]),
    dict(name="Srinagar", titles=["Srinagar, Uttarakhand"], district="Pauri Garhwal", region="Garhwal",
         search_ctx="Srinagar Garhwal Alaknanda town",
         highlight_candidates=["Dhari Devi", "Alaknanda", "Hemwati Nandan Bahuguna"]),
    dict(name="Devprayag", titles=["Devprayag"], district="Pauri Garhwal", region="Garhwal",
         search_ctx="Devprayag confluence Bhagirathi Alaknanda",
         highlight_candidates=["Bhagirathi", "Alaknanda", "Raghunath"]),
    dict(name="Karnaprayag", titles=["Karnaprayag"], district="Chamoli", region="Garhwal",
         search_ctx="Karnaprayag confluence Pindar Alaknanda",
         highlight_candidates=["Pindar", "Alaknanda", "Karna"]),
    dict(name="Nandaprayag", titles=["Nandaprayag"], district="Chamoli", region="Garhwal",
         search_ctx="Nandaprayag confluence Uttarakhand",
         highlight_candidates=["Nandakini", "Alaknanda"]),
    dict(name="Vishnuprayag", titles=["Vishnuprayag"], district="Chamoli", region="Garhwal",
         search_ctx="Vishnuprayag confluence Dhauliganga",
         highlight_candidates=["Dhauliganga", "Alaknanda", "Badri"]),
    dict(name="Sonprayag", titles=["Sonprayag"], district="Rudraprayag", region="Garhwal",
         search_ctx="Sonprayag Kedarnath route",
         highlight_candidates=["Kedarnath", "Mandakini"]),
    dict(name="Gopeshwar", titles=["Chamoli Gopeshwar", "Gopeshwar"], district="Chamoli", region="Garhwal",
         search_ctx="Gopeshwar Chamoli town",
         highlight_candidates=["Gopinath Temple", "Auli", "Trishul"]),
    dict(name="Govindghat", titles=["Govindghat"], district="Chamoli", region="Garhwal",
         search_ctx="Govindghat Valley of Flowers Hemkund ghat",
         highlight_candidates=["Valley of Flowers", "Hemkund", "Lakshman Ganga"]),
    dict(name="Mana", titles=["Mana, Chamoli"], district="Chamoli", region="Garhwal",
         search_ctx="Mana village last India Tibet border",
         highlight_candidates=["Vyas Gufa", "Bhim Pul", "Saraswati"]),
    dict(name="Ghangaria", titles=["Ghangaria"], district="Chamoli", region="Garhwal",
         search_ctx="Ghangaria Hemkund Valley of Flowers base",
         highlight_candidates=["Hemkund", "Valley of Flowers", "Pushpawati"]),
    dict(name="Sankri", titles=["Sankri"], district="Uttarkashi", region="Garhwal",
         search_ctx="Sankri village Har Ki Dun Kedarkantha",
         highlight_candidates=["Har Ki Dun", "Kedarkantha", "Swargarohini"]),
    dict(name="Barkot", titles=["Barkot, Uttarakhand"], district="Uttarkashi", region="Garhwal",
         search_ctx="Barkot Yamunotri Uttarakhand",
         highlight_candidates=["Yamunotri", "Barkot"]),
    dict(name="Chamba", titles=["Chamba, Uttarakhand"], district="Tehri Garhwal", region="Garhwal",
         search_ctx="Chamba Tehri Uttarakhand town",
         highlight_candidates=["Tehri Dam", "Surkanda Devi", "Bhagirathi"]),
    dict(name="Tehri Dam", titles=["Tehri Dam"], district="Tehri Garhwal", region="Garhwal",
         search_ctx="Tehri Dam lake Uttarakhand",
         highlight_candidates=["Tehri Lake", "Bhagirathi", "Bhilangana"]),
    dict(name="Gaumukh", titles=["Gomukh", "Gangotri Glacier"], district="Uttarkashi", region="Garhwal",
         search_ctx="Gaumukh Gangotri glacier snout source of Ganges",
         highlight_candidates=["Gangotri Glacier", "Bhagirathi", "source"]),
    dict(name="Vasudhara Falls", titles=["Vasudhara Falls"], district="Chamoli", region="Garhwal",
         search_ctx="Vasudhara Falls Badrinath Uttarakhand",
         highlight_candidates=["Badrinath", "Alaknanda"]),
    dict(name="Bedni Bugyal", titles=["Bedni Bugyal"], district="Chamoli", region="Garhwal",
         search_ctx="Bedni Bugyal meadow Roopkund",
         highlight_candidates=["Roopkund", "Nanda Devi Raj Jat", "Ali Bugyal"]),
    dict(name="Panwali Kantha Bugyal", titles=["Panwali Kantha Bugyal", "Panwali Kantha"], district="Tehri Garhwal", region="Garhwal",
         search_ctx="Panwali Kantha bugyal meadow Uttarakhand",
         highlight_candidates=["bugyal", "Ghuttu"]),
    dict(name="Gangotri National Park", titles=["Gangotri National Park"], district="Uttarkashi", region="Garhwal",
         search_ctx="Gangotri National Park Uttarakhand",
         highlight_candidates=["Gaumukh", "snow leopard", "bharal"]),
    dict(name="Govind Pashu Vihar National Park", titles=["Govind Pashu Vihar National Park", "Govind Pashu Vihar"], district="Uttarkashi", region="Garhwal",
         search_ctx="Govind Pashu Vihar National Park Har Ki Dun",
         highlight_candidates=["Har Ki Dun", "snow leopard", "black bear"]),
    dict(name="Nanda Devi National Park", titles=["Nanda Devi National Park"], district="Chamoli", region="Garhwal",
         search_ctx="Nanda Devi National Park UNESCO",
         highlight_candidates=["UNESCO", "Nanda Devi", "Rishi Ganga"]),
    dict(name="Askot Musk Deer Sanctuary", titles=["Askot Musk Deer Sanctuary"], district="Pithoragarh", region="Kumaon",
         search_ctx="Askot Musk Deer Sanctuary Pithoragarh",
         highlight_candidates=["musk deer"]),
    dict(name="Kedarnath Wildlife Sanctuary", titles=["Kedarnath Wildlife Sanctuary", "Kedarnath Musk Deer Sanctuary"], district="Rudraprayag", region="Garhwal",
         search_ctx="Kedarnath Wildlife Sanctuary Uttarakhand",
         highlight_candidates=["musk deer", "Kedarnath", "monal"]),
    dict(name="Asan Barrage", titles=["Asan Barrage"], district="Dehradun", region="Garhwal",
         search_ctx="Asan Barrage wetland birds Dehradun",
         highlight_candidates=["migratory", "Yamuna", "birdwatching"]),
    # --- Kumaon towns / hill stations ---
    dict(name="Haldwani", titles=["Haldwani"], district="Nainital", region="Kumaon",
         search_ctx="Haldwani gateway Kumaon Uttarakhand",
         highlight_candidates=["gateway", "Kumaon", "Gaula"]),
    dict(name="Kaladhungi", titles=["Kaladhungi"], district="Nainital", region="Kumaon",
         search_ctx="Kaladhungi Jim Corbett Chhoti Haldwani",
         highlight_candidates=["Jim Corbett", "Chhoti Haldwani", "Corbett Museum"]),
    dict(name="Dhanachuli", titles=["Dhanachuli"], district="Nainital", region="Kumaon",
         search_ctx="Dhanachuli village Nainital Himalayas",
         highlight_candidates=["Himalaya", "village"]),
    dict(name="Pangot", titles=["Pangot"], district="Nainital", region="Kumaon",
         search_ctx="Pangot Kilbury birding Nainital",
         highlight_candidates=["Kilbury", "bird"]),
    dict(name="Ramgarh", titles=["Ramgarh, Uttarakhand"], district="Nainital", region="Kumaon",
         search_ctx="Ramgarh orchards Nainital Kumaon",
         highlight_candidates=["orchard", "Nathuakhan", "Tagore"]),
    dict(name="Bhowali", titles=["Bhowali"], district="Nainital", region="Kumaon",
         search_ctx="Bhowali Uttarakhand town",
         highlight_candidates=["Ghorakhal", "Sattal"]),
    dict(name="Jeolikot", titles=["Jeolikot", "Jeolikote"], district="Nainital", region="Kumaon",
         search_ctx="Jeolikot Nainital butterflies",
         highlight_candidates=["butterfl", "Nainital"]),
    dict(name="Vijaypur", titles=["Vijaypur, Uttarakhand"], district="Bageshwar", region="Kumaon",
         search_ctx="Vijaypur Bageshwar Kausani viewpoint",
         highlight_candidates=["Kausani", "Himalaya"]),
    dict(name="Someshwar", titles=["Someshwar, Uttarakhand"], district="Almora", region="Kumaon",
         search_ctx="Someshwar valley Almora Uttarakhand",
         highlight_candidates=["Someshwar", "valley"]),
    dict(name="Chaukhutia", titles=["Chaukhutia"], district="Almora", region="Kumaon",
         search_ctx="Chaukhutia Almora Kali river",
         highlight_candidates=["Kali", "ruins"]),
    dict(name="Berinag", titles=["Berinag"], district="Pithoragarh", region="Kumaon",
         search_ctx="Berinag Pithoragarh hill station tea",
         highlight_candidates=["tea", "Himalaya"]),
    dict(name="Didihat", titles=["Didihat"], district="Pithoragarh", region="Kumaon",
         search_ctx="Didihat Pithoragarh Uttarakhand",
         highlight_candidates=["Panchachuli", "Himalaya"]),
    dict(name="Dharchula", titles=["Dharchula"], district="Pithoragarh", region="Kumaon",
         search_ctx="Dharchula Kali river Nepal border",
         highlight_candidates=["Kali River", "Nepal", "Kailash"]),
    dict(name="Gangolihat", titles=["Gangolihat"], district="Pithoragarh", region="Kumaon",
         search_ctx="Gangolihat Haat Kalika Patal Bhuvaneshwar",
         highlight_candidates=["Kali", "Patal Bhuvaneshwar"]),
    dict(name="Champawat", titles=["Champawat"], district="Champawat", region="Kumaon",
         search_ctx="Champawat Uttarakhand Katyuri historic town",
         highlight_candidates=["Baleshwar", "Katyuri", "Chand"]),
    dict(name="Darma Valley", titles=["Darma Valley", "Darma valley"], district="Pithoragarh", region="Kumaon",
         search_ctx="Darma Valley Pithoragarh trek",
         highlight_candidates=["Darma", "Om Parvat", "tribal"]),
    dict(name="Johar Valley", titles=["Johar Valley", "Johar valley"], district="Pithoragarh", region="Kumaon",
         search_ctx="Johar Valley Munsiyari Milam glacier",
         highlight_candidates=["Milam", "Munsiyari", "Gori"]),
    dict(name="Niti Valley", titles=["Niti Valley"], district="Chamoli", region="Garhwal",
         search_ctx="Niti Valley Chamoli Malari border",
         highlight_candidates=["Malari", "Niti", "Dhauliganga"]),
]

SPIRITUAL += [
    dict(name="Triyuginarayan Temple", titles=["Triyuginarayan Temple", "Triyuginarayan"], district="Rudraprayag", region="Garhwal",
         location="Sonprayag–Guptakashi area", search_ctx="Triyuginarayan temple wedding Shiva Parvati",
         highlight_candidates=["wedding", "Shiva", "Parvati", "Agni", "eternal flame"]),
    dict(name="Kalimath", titles=["Kalimath"], district="Rudraprayag", region="Garhwal",
         location="Near Guptakashi", search_ctx="Kalimath temple Kali Rudraprayag",
         highlight_candidates=["Kali", "Saraswati", "Lakshmi"]),
    dict(name="Koteshwar Mahadev Temple", titles=["Koteshwar Mahadev"], district="Rudraprayag", region="Garhwal",
         location="Rudraprayag, Alaknanda bank", search_ctx="Koteshwar Mahadev cave temple Rudraprayag",
         highlight_candidates=["cave", "Alaknanda", "Shiva"]),
    dict(name="Gauri Kund", titles=["Gauri Kund"], district="Rudraprayag", region="Garhwal",
         location="Base of Kedarnath trek", search_ctx="Gauri Kund temple hot spring Kedarnath",
         highlight_candidates=["Kedarnath", "Parvati", "hot spring"]),
    dict(name="Chandrabadani Devi", titles=["Chandrabadani Devi", "Chandrabadani"], district="Tehri Garhwal", region="Garhwal",
         location="Chandrabadani hill, Tehri–Devprayag road", search_ctx="Chandrabadani Devi temple Tehri",
         highlight_candidates=["Sati", "goddess", "Shakti Peeth"]),
    dict(name="Jwalpa Devi Temple", titles=["Jwalpa Devi"], district="Pauri Garhwal", region="Garhwal",
         location="Near Pauri", search_ctx="Jwalpa Devi temple Pauri Garhwal",
         highlight_candidates=["Durga", "goddess"]),
    dict(name="Raghunath Temple, Devprayag", titles=["Raghunath Temple, Devprayag"], district="Pauri Garhwal", region="Garhwal",
         location="Devprayag", search_ctx="Raghunath temple Devprayag Rama",
         highlight_candidates=["Rama", "confluence", "Bhagirathi"]),
    dict(name="Mahasu Devta Temple", titles=["Mahasu Devta Temple", "Mahasu Devta"], district="Dehradun", region="Garhwal",
         location="Hanol, Jaunsar-Bawar", search_ctx="Mahasu Devta temple Hanol",
         highlight_candidates=["Hanol", "Mahasu", "deity"]),
    dict(name="Lakhamandal", titles=["Lakhamandal"], district="Dehradun", region="Garhwal",
         location="Jaunsar-Bawar, near Mussoorie–Chakrata", search_ctx="Lakhamandal temple Mahabharata Pandavas",
         highlight_candidates=["Mahabharata", "Pandavas", "Shiva", "Kauravas"]),
    dict(name="Beatles Ashram", titles=["Beatles Ashram", "Chaurasi Kutia"], district="Dehradun", region="Garhwal",
         location="Rishikesh", search_ctx="Beatles Ashram Maharishi Rishikesh Chaurasi Kutia",
         highlight_candidates=["Maharishi", "Beatles", "Transcendental Meditation"]),
    dict(name="Divine Life Society", titles=["Divine Life Society"], district="Dehradun", region="Garhwal",
         location="Rishikesh", search_ctx="Divine Life Society Sivananda Ashram Rishikesh",
         highlight_candidates=["Sivananda", "Rishikesh", "yoga"]),
    dict(name="Mindrolling Monastery", titles=["Mindrolling Monastery"], district="Dehradun", region="Garhwal",
         location="Clement Town, Dehradun", search_ctx="Mindrolling Monastery Dehradun Great Stupa",
         highlight_candidates=["Nyingma", "stupa", "Tibetan"]),
    dict(name="Guru Ram Rai Darbar Sahib", titles=["Guru Ram Rai Darbar Sahib"], district="Dehradun", region="Garhwal",
         location="Dehradun", search_ctx="Guru Ram Rai Darbar Sahib gurdwara Dehradun",
         highlight_candidates=["Guru Ram Rai", "Dehradun", "Sikh"]),
    dict(name="Jyotir Math", titles=["Jyotir Math"], district="Chamoli", region="Garhwal",
         location="Joshimath", search_ctx="Jyotir Math Joshimath Shankaracharya",
         highlight_candidates=["Shankaracharya", "Badri", "matha"]),
    dict(name="Gopinath Temple, Gopeshwar", titles=["Gopinath Temple, Gopeshwar"], district="Chamoli", region="Garhwal",
         location="Gopeshwar", search_ctx="Gopinath temple Gopeshwar trishul",
         highlight_candidates=["trishul", "Gopeshwar", "Shiva"]),
    dict(name="Adi Badri", titles=["Adi Badri"], district="Chamoli", region="Garhwal",
         location="Karnaprayag area", search_ctx="Adi Badri temple Sapta Badri",
         highlight_candidates=["Sapta Badri", "Vishnu", "Gupta"]),
    dict(name="Binsar Mahadev Temple", titles=["Binsar Mahadev"], district="Almora", region="Kumaon",
         location="Near Ranikhet", search_ctx="Binsar Mahadev temple Ranikhet",
         highlight_candidates=["Ranikhet", "Shiva"]),
    dict(name="Bagnath Temple", titles=["Bagnath Temple"], district="Bageshwar", region="Kumaon",
         location="Bageshwar", search_ctx="Bagnath temple Bageshwar Shiva Sarayu",
         highlight_candidates=["Shiva", "Sarayu", "Bageshwar"]),
    dict(name="Garjiya Devi Temple", titles=["Garjiya Devi"], district="Nainital", region="Kumaon",
         location="Ramnagar, near Corbett", search_ctx="Garjiya Devi temple Ramnagar Corbett",
         highlight_candidates=["Corbett", "Kosi", "goddess"]),
    dict(name="Ghorakhal", titles=["Ghorakhal"], district="Nainital", region="Kumaon",
         location="Near Bhowali", search_ctx="Ghorakhal Golu Devta temple Sainik School",
         highlight_candidates=["Golu Devta", "Sainik School"]),
    dict(name="Hanumangarhi, Nainital", titles=["Hanumangarhi, Nainital"], district="Nainital", region="Kumaon",
         location="Nainital", search_ctx="Hanumangarhi temple Nainital Hanuman hill",
         highlight_candidates=["Hanuman", "sunset"]),
    dict(name="Nanakmatta", titles=["Nanakmatta"], district="Udham Singh Nagar", region="Kumaon",
         location="Near Khatima–Sitarganj", search_ctx="Nanakmatta gurdwara Guru Nanak Udham Singh Nagar",
         highlight_candidates=["Guru Nanak", "gurdwara", "Sikh"]),
    dict(name="Baleshwar Temple", titles=["Baleshwar Temple"], district="Champawat", region="Kumaon",
         location="Champawat", search_ctx="Baleshwar temple Champawat Katyuri Shiva",
         highlight_candidates=["Katyuri", "Shiva", "Champawat"]),
    dict(name="Gurdwara Gyan Godri Sahib", titles=["Gurdwara Gyan Godri Sahib"], district="Haridwar", region="Garhwal",
         location="Har Ki Pauri, Haridwar", search_ctx="Gyan Godri gurdwara Haridwar Guru Nanak",
         highlight_candidates=["Guru Nanak", "Har Ki Pauri", "Ganga"]),
    dict(name="Daksheswar Mahadev Temple", titles=["Daksheswar Mahadev Temple", "Daksha Mahadev temple"], district="Haridwar", region="Garhwal",
         location="Kankhal, Haridwar", search_ctx="Daksheswar Mahadev temple Kankhal Sati",
         highlight_candidates=["Daksha", "Sati", "Kankhal"]),
    dict(name="Satopanth Tal", titles=["Satopanth Tal"], district="Chamoli", region="Garhwal",
         location="Above Badrinath", search_ctx="Satopanth Tal sacred lake Badrinath",
         highlight_candidates=["Chaukhamba", "Brahma", "Vishnu", "Mahesh"]),
]

CULTURAL += [
    dict(name="Haridwar Kumbh Mela", titles=["Haridwar Kumbh Mela", "Kumbh Mela"], district="Haridwar", region="Garhwal",
         location="Har Ki Pauri, Haridwar", search_ctx="Kumbh Mela Haridwar Har Ki Pauri",
         highlight_candidates=["Har Ki Pauri", "Ganga", "millions", "pilgrims"]),
    dict(name="Kanwar Yatra", titles=["Kanwar Yatra"], district="Haridwar", region="Garhwal",
         location="Haridwar–Ganga canal route", search_ctx="Kanwar Yatra Haridwar Ganga devotees",
         highlight_candidates=["Ganga", "Shiva", "kanwar"]),
    dict(name="Harela", titles=["Harela"], district="Multiple (Uttarakhand)", region="Kumaon",
         location="Uttarakhand (Kumaon)", search_ctx="Harela festival Uttarakhand greenery",
         highlight_candidates=["seeds", "green", "monsoon", "festival"]),
    dict(name="Igas Bagwal", titles=["Igas Bagwal"], district="Multiple (Uttarakhand)", region="Garhwal",
         location="Garhwal", search_ctx="Igas Bagwal festival Garhwal Diwali",
         highlight_candidates=["Diwali", "Pandavas", "fire"]),
    dict(name="Kandali Festival", titles=["Kandali Festival"], district="Pithoragarh", region="Kumaon",
         location="Darma/Johar valleys, Pithoragarh", search_ctx="Kandali festival Pithoragarh Rang community",
         highlight_candidates=["Rang", "buckwheat", "twelve"]),
    dict(name="Kumaoni Holi", titles=["Kumaoni Holi"], district="Multiple (Uttarakhand)", region="Kumaon",
         location="Kumaon", search_ctx="Kumaoni Holi Baithki Khari Holi songs",
         highlight_candidates=["Baithki", "Khari", "Mahila", "songs"]),
    dict(name="Pandav Lila", titles=["Pandav Lila"], district="Multiple (Uttarakhand)", region="Garhwal",
         location="Garhwal villages", search_ctx="Pandav Lila folk theatre Garhwal Mahabharata",
         highlight_candidates=["Pandavas", "Mahabharata", "drum", "dance"]),
    dict(name="Ramman", titles=["Ramman (festival)"], district="Chamoli", region="Garhwal",
         location="Saloor–Dungra villages, Chamoli", search_ctx="Ramman festival UNESCO Saloor Dungra Chamoli",
         highlight_candidates=["UNESCO", "Saloor", "Dungra", "Bhumiyal"]),
    dict(name="Virasat", titles=["Virasat (festival)"], district="Dehradun", region="Garhwal",
         location="Dehradun", search_ctx="Virasat festival Dehradun heritage arts",
         highlight_candidates=["heritage", "arts", "festival"]),
    dict(name="Chholiya", titles=["Chholiya"], district="Multiple (Uttarakhand)", region="Kumaon",
         location="Kumaon", search_ctx="Chholiya sword dance Kumaon wedding",
         highlight_candidates=["sword", "wedding", "dance", "Kumaon"]),
    dict(name="Jagar", titles=["Jagar (ritual)"], district="Multiple (Uttarakhand)", region="Garhwal",
         location="Garhwal–Kumaon", search_ctx="Jagar ritual Uttarakhand spirit possession folk",
         highlight_candidates=["possession", "spirits", "ritual", "night"]),
    dict(name="Kumaoni cuisine", titles=["Kumaoni cuisine"], district="Multiple (Uttarakhand)", region="Kumaon",
         location="Kumaon", search_ctx="Kumaoni cuisine bal mithai bhatt dubka",
         highlight_candidates=["Bal mithai", "bhatt", "Dubka", "Jholi", "buckwheat"]),
    dict(name="Bal mithai", titles=["Bal mithai"], district="Almora", region="Kumaon",
         location="Almora", search_ctx="Bal mithai sweet Almora Kumaon khoya",
         highlight_candidates=["khoya", "Almora", "sweet", "poppy"]),
    dict(name="Lakhudiyar Caves", titles=["Lakhudiyar Caves"], district="Almora", region="Kumaon",
         location="Almora", search_ctx="Lakhudiyar caves rock paintings Almora",
         highlight_candidates=["rock", "paintings", "prehistoric"]),
    dict(name="Rock Edicts of Khalsi", titles=["Rock edicts of Khalsi", "Kalsi"], district="Dehradun", region="Garhwal",
         location="Kalsi, Dehradun", search_ctx="Kalsi rock edicts Ashoka Dehradun",
         highlight_candidates=["Ashoka", "edicts", "Mauryan"]),
    dict(name="Khalanga War Memorial", titles=["Khalanga War Memorial"], district="Dehradun", region="Garhwal",
         location="Dehradun", search_ctx="Khalanga War Memorial Anglo Nepalese Nalapani Dehradun",
         highlight_candidates=["Nalapani", "Gurkha", "Anglo-Nepalese", "Balbhadra"]),
    dict(name="St. Paul's Church, Landour", titles=["St. Paul's Church, Landour"], district="Dehradun", region="Garhwal",
         location="Landour, Mussoorie", search_ctx="St Paul's Church Landour Mussoorie",
         highlight_candidates=["Landour", "church", "British"]),
    dict(name="Kipling Trail", titles=["Kipling Trail"], district="Dehradun", region="Garhwal",
         location="Mussoorie–Landour", search_ctx="Kipling Trail Mussoorie Landour walk",
         highlight_candidates=["Kipling", "Landour", "walk"]),
    dict(name="Cranks' Ridge", titles=["Cranks' Ridge"], district="Almora", region="Kumaon",
         location="Kasar Devi, Almora", search_ctx="Cranks Ridge Kasar Devi Almora hippie",
         highlight_candidates=["Kasar Devi", "hippie", "Lawrence", "sunrise"]),
    dict(name="Hindu Genealogy Registers at Haridwar", titles=["Hindu genealogy registers at Haridwar"], district="Haridwar", region="Garhwal",
         location="Haridwar", search_ctx="Haridwar genealogy registers pandas Brahmin records",
         highlight_candidates=["pandas", "registers", "ancestors", "pilgrims"]),
]

ACTIVITIES += [
    dict(name="Kedarkantha Trek", titles=["Kedarkantha"], district="Uttarkashi", region="Garhwal",
         location="Sankri, Uttarkashi", category="Trekking", search_ctx="Kedarkantha trek winter snow Sankri",
         highlight_candidates=["Swargarohini", "snow", "winter", "summit"]),
    dict(name="Kafni Glacier Trek", titles=["Kafni Glacier"], district="Bageshwar", region="Kumaon",
         location="Loharkhet–Dhakuri route, Bageshwar", category="Trekking", search_ctx="Kafni Glacier trek Pindari Nanda Khat",
         highlight_candidates=["Nanda Khat", "Pindari", "glacier"]),
    dict(name="Khatling Glacier Trek", titles=["Khatling Glacier"], district="Tehri Garhwal", region="Garhwal",
         location="Ghuttu, Tehri Garhwal", category="Trekking", search_ctx="Khatling Glacier trek Bhilangna Sahasratal",
         highlight_candidates=["Bhilangna", "Sahasratal", "glacier"]),
    dict(name="Satopanth Tal Trek", titles=["Satopanth Tal"], district="Chamoli", region="Garhwal",
         location="Above Badrinath", category="Trekking", search_ctx="Satopanth Tal trek Badrinath Chaukhamba",
         highlight_candidates=["Chaukhamba", "Brahma", "Vishnu", "Mahesh"]),
    dict(name="Panch Kedar Yatra", titles=["Panch Kedar"], district="Multiple (Uttarakhand)", region="Garhwal",
         location="Garhwal (Rudraprayag–Chamoli–Almora)", category="Pilgrimage", search_ctx="Panch Kedar yatra five Shiva temples",
         highlight_candidates=["Kedarnath", "Tungnath", "Rudranath", "Madhyamaheshwar", "Kalpeshwar"]),
]
'''

path = "scripts/config.py"
src = open(path, encoding="utf-8").read()
assert "EXPANSION BATCH 1" not in src, "already patched"
open(path, "w", encoding="utf-8").write(src + PATCH)

# sanity: import and count
import importlib, sys
sys.path.insert(0, "scripts")
import config
importlib.reload(config)
print("DESTINATIONS:", len(config.DESTINATIONS))
print("SPIRITUAL:", len(config.SPIRITUAL))
print("CULTURAL:", len(config.CULTURAL))
print("ACTIVITIES:", len(config.ACTIVITIES))
names = ([d["name"] for d in config.DESTINATIONS] + [s["name"] for s in config.SPIRITUAL] +
         [c["name"] for c in config.CULTURAL] + [a["name"] for a in config.ACTIVITIES])
assert len(names) == len(set(names)), "DUPLICATE NAMES IN CONFIG"
print("total entities:", len(names), "| no duplicate names ✓")
